# -*- coding: utf-8 -*-
"""01_clean_atlas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JtY5Ox0Xk-YUcFlpljP-Y5vPx5FT48Pf
"""

# =============================================================================
# SETUP AND DATA IMPORT
# =============================================================================

from pathlib import Path

import pandas as pd


# -----------------------------------------------------------------------------
# Configure the project directory
# -----------------------------------------------------------------------------

try:
    from google.colab import drive
except ImportError:
    drive = None


if drive is not None:
    # Google Colab: mount Drive and use the existing project location.
    drive.mount("/content/drive")

    project_dir = Path(
        "/content/drive/MyDrive/AMR Data Challenge 2026/"
        "Harmonized Database Creation"
    )
else:
    # Local execution: start the notebook from the project directory.
    project_dir = Path.cwd()


# -----------------------------------------------------------------------------
# Define and validate the input file
# -----------------------------------------------------------------------------

input_file = project_dir / "Raw" / "Atlas.csv"

if not input_file.is_file():
    raise FileNotFoundError(
        "ATLAS input file not found. "
        f"Expected location: {input_file}"
    )


# -----------------------------------------------------------------------------
# Load the ATLAS dataset
# -----------------------------------------------------------------------------

df = pd.read_csv(
    input_file,
    low_memory=False,
)


# Store the original dimensions for final validation
original_shape = df.shape


# -----------------------------------------------------------------------------
# Confirm successful import
# -----------------------------------------------------------------------------

print("ATLAS dataset loaded successfully.")
print(f"Rows: {df.shape[0]:,}")
print(f"Columns: {df.shape[1]:,}")
print(f"Input: {input_file}")

# =============================================================================
# CORE ATLAS HARMONIZATION
# =============================================================================

# -----------------------------------------------------------------------------
# Validate required columns before transformation
# -----------------------------------------------------------------------------

required_columns = ["Species", "Country"]

missing_columns = [
    col for col in required_columns
    if col not in df.columns
]

if missing_columns:
    raise KeyError(
        f"Required columns missing from ATLAS: {missing_columns}"
    )

if "Organism" in df.columns:
    raise ValueError(
        "'Organism' column already exists. Review before renaming 'Species'."
    )


# -----------------------------------------------------------------------------
# Add source database variable
# -----------------------------------------------------------------------------

df["Source Database"] = "Atlas"


# -----------------------------------------------------------------------------
# Harmonize country name
# -----------------------------------------------------------------------------

n_korea_before = (df["Country"] == "Korea, South").sum()

df["Country"] = df["Country"].replace({
    "Korea, South": "South Korea"
})


# -----------------------------------------------------------------------------
# Harmonize organism column name
# -----------------------------------------------------------------------------

df = df.rename(columns={
    "Species": "Organism"
})


# -----------------------------------------------------------------------------
# Validation checks
# -----------------------------------------------------------------------------

assert df["Source Database"].eq("Atlas").all()
assert "Species" not in df.columns
assert "Organism" in df.columns
assert (df["Country"] == "Korea, South").sum() == 0
assert (df["Country"] == "South Korea").sum() >= n_korea_before


print("Core ATLAS harmonization completed.")
print(f"Source Database: {df['Source Database'].unique().tolist()}")
print(f"'Korea, South' values changed: {n_korea_before:,}")
print("Column renamed: Species → Organism")
print(f"Current shape: {df.shape}")

# -----------------------------------------------------------------------------
# Reclassify intermediate interpretations as susceptible
# -----------------------------------------------------------------------------

# Identify all antimicrobial interpretation columns
interpretation_columns = [
    col for col in df.columns
    if col.endswith("_I")
]

if not interpretation_columns:
    raise ValueError(
        "No antimicrobial interpretation columns ending in '_I' were found."
    )


# Count Intermediate values before recoding
intermediate_by_column = (
    df[interpretation_columns]
    .eq("Intermediate")
    .sum()
)

intermediate_by_column = intermediate_by_column[
    intermediate_by_column > 0
].sort_values(ascending=False)

n_intermediate_before = int(intermediate_by_column.sum())


# Reclassify Intermediate as Susceptible
df[interpretation_columns] = (
    df[interpretation_columns]
    .replace({
        "Intermediate": "Susceptible"
    })
)


# Validate recoding
n_intermediate_after = int(
    df[interpretation_columns]
    .eq("Intermediate")
    .sum()
    .sum()
)

assert n_intermediate_after == 0


# Report changes
print("ATLAS interpretation recoding completed.")
print(f"Interpretation columns identified: {len(interpretation_columns)}")
print(
    "Intermediate values changed to Susceptible: "
    f"{n_intermediate_before:,}"
)

print("\nIntermediate values changed by antibiotic:")
print(intermediate_by_column.to_string())

# =============================================================================
# SAVE HARMONIZED ATLAS DATASET
# =============================================================================

# -----------------------------------------------------------------------------
# Validate the final dataset dimensions
# -----------------------------------------------------------------------------

# Harmonization adds one column ("Source Database") without changing
# the number of rows.
expected_shape = (
    original_shape[0],
    original_shape[1] + 1,
)

if df.shape != expected_shape:
    raise ValueError(
        "Unexpected dimensions after ATLAS harmonization. "
        f"Expected {expected_shape}, found {df.shape}."
    )


# -----------------------------------------------------------------------------
# Define the output directory and files
# -----------------------------------------------------------------------------

output_dir = project_dir / "Cleaned"
output_dir.mkdir(parents=True, exist_ok=True)

output_parquet = output_dir / "Atlas_harmonized.parquet"
output_csv = output_dir / "Atlas_harmonized.csv"


# -----------------------------------------------------------------------------
# Save the harmonized dataset
# -----------------------------------------------------------------------------

df.to_parquet(
    output_parquet,
    index=False,
)

df.to_csv(
    output_csv,
    index=False,
)


# -----------------------------------------------------------------------------
# Validate the exported files
# -----------------------------------------------------------------------------

for output_file in (output_parquet, output_csv):
    if not output_file.is_file() or output_file.stat().st_size == 0:
        raise OSError(
            f"Output file was not created successfully: {output_file}"
        )


# -----------------------------------------------------------------------------
# Confirm successful export
# -----------------------------------------------------------------------------

print("Harmonized ATLAS dataset saved successfully.")
print(f"Rows: {df.shape[0]:,}")
print(f"Columns: {df.shape[1]:,}")
print(f"Parquet: {output_parquet}")
print(f"CSV:     {output_csv}")