# -*- coding: utf-8 -*-
"""02_clean_acinetobacter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XotO6-kSaxkRfS4N7pvhLAMNnVYmFJb0
"""

# =============================================================================
# SETUP AND DATA IMPORT
# =============================================================================

from pathlib import Path

import pandas as pd


# -----------------------------------------------------------------------------
# Configure the project directory
# -----------------------------------------------------------------------------

try:
    from google.colab import drive
except ImportError:
    drive = None


if drive is not None:
    # Google Colab: mount Drive and use the existing project location.
    drive.mount("/content/drive")

    project_dir = Path(
        "/content/drive/MyDrive/AMR Data Challenge 2026/"
        "Harmonized Database Creation"
    )
else:
    # Local execution: start the notebook from the project directory.
    project_dir = Path.cwd()


# -----------------------------------------------------------------------------
# Define and validate the input file
# -----------------------------------------------------------------------------

input_file = project_dir / "Raw" / "Acinetobacter.xlsx"

if not input_file.is_file():
    raise FileNotFoundError(
        "Acinetobacter input file not found. "
        f"Expected location: {input_file}"
    )


# -----------------------------------------------------------------------------
# Load the raw Acinetobacter dataset
# -----------------------------------------------------------------------------

df = pd.read_excel(input_file)


# -----------------------------------------------------------------------------
# Confirm successful import
# -----------------------------------------------------------------------------

print("Acinetobacter dataset loaded successfully.")
print(f"Rows: {df.shape[0]:,}")
print(f"Columns: {df.shape[1]:,}")
print(f"Input: {input_file}")

# =============================================================================
# HARMONIZE CORE METADATA
# =============================================================================

# Record original dataset dimensions for validation
original_shape = df.shape


# -----------------------------------------------------------------------------
# Verify required source columns
# -----------------------------------------------------------------------------

required_columns = [
    "Vivli No.",
    "OrganismName",
    "Country",
    "YearCollected",
]

missing_columns = [
    col for col in required_columns
    if col not in df.columns
]

if missing_columns:
    raise KeyError(
        f"Expected source columns not found: {missing_columns}"
    )


# -----------------------------------------------------------------------------
# Rename harmonized metadata columns
# -----------------------------------------------------------------------------

rename_map = {
    "Vivli No.": "Isolate Id",
    "OrganismName": "Organism",
    "YearCollected": "Year",
}

df = df.rename(columns=rename_map)


# -----------------------------------------------------------------------------
# Add source database provenance
# -----------------------------------------------------------------------------

df["Source Database"] = "Acinetobacter"


# -----------------------------------------------------------------------------
# Harmonize confirmed country name difference
# -----------------------------------------------------------------------------

country_map = {
    "Korea, South": "South Korea",
}

df["Country"] = df["Country"].replace(country_map)


# -----------------------------------------------------------------------------
# Validation checks
# -----------------------------------------------------------------------------

# Confirm that row count is unchanged
assert df.shape[0] == original_shape[0], (
    "Row count changed during metadata harmonization."
)


# Confirm that renamed columns are present
expected_columns = [
    "Isolate Id",
    "Organism",
    "Country",
    "Year",
    "Source Database",
]

missing_harmonized_columns = [
    col for col in expected_columns
    if col not in df.columns
]

if missing_harmonized_columns:
    raise KeyError(
        f"Expected harmonized columns not found: "
        f"{missing_harmonized_columns}"
    )


# Confirm provenance value
assert df["Source Database"].eq("Acinetobacter").all(), (
    "Unexpected values found in Source Database."
)


# Confirm country harmonization
assert not df["Country"].eq("Korea, South").any(), (
    "'Korea, South' remains in the Country column."
)


# Confirm changes
print("Core metadata harmonization completed successfully.")
print(f"Rows: {df.shape[0]:,}")
print(f"Columns: {df.shape[1]:,}")

print("\nSelected harmonized columns:")
print(
    df[
        [
            "Isolate Id",
            "Source Database",
            "Organism",
            "Country",
            "Year",
        ]
    ].head()
)

# =============================================================================
# HARMONIZE GENDER
# =============================================================================

# Standardize surrounding whitespace while preserving missing values
gender_clean = (
    df["Gender"]
    .astype("string")
    .str.strip()
)


# -----------------------------------------------------------------------------
# Validate source values
# -----------------------------------------------------------------------------

expected_gender_values = {"M", "F"}

unexpected_gender_values = (
    set(gender_clean.dropna().unique())
    - expected_gender_values
)

if unexpected_gender_values:
    raise ValueError(
        f"Unexpected Gender values found: "
        f"{sorted(unexpected_gender_values)}"
    )


# Record missing values before harmonization
n_missing_gender = gender_clean.isna().sum()

print(f"Missing Gender values before harmonization: {n_missing_gender:,}")


# -----------------------------------------------------------------------------
# Harmonize Gender values
# -----------------------------------------------------------------------------

gender_map = {
    "M": "Male",
    "F": "Female",
}

df["Gender"] = (
    gender_clean
    .map(gender_map)
    .fillna("Unknown")
)


# -----------------------------------------------------------------------------
# Validation checks
# -----------------------------------------------------------------------------

expected_harmonized_values = {
    "Male",
    "Female",
    "Unknown",
}

assert set(df["Gender"].unique()) <= expected_harmonized_values, (
    "Unexpected values found in harmonized Gender column."
)

assert df["Gender"].eq("Unknown").sum() == n_missing_gender, (
    "The number of Unknown Gender values does not match "
    "the original number of missing values."
)


# Confirm results
print("\nGender harmonization completed successfully.")
print(df["Gender"].value_counts(dropna=False))

# =============================================================================
# CLEAN AGE AND CREATE AGE GROUP
# =============================================================================

# Convert Age to numeric for validation and grouping
age_num = pd.to_numeric(
    df["Age"],
    errors="coerce"
)


# -----------------------------------------------------------------------------
# Review age range and invalid values
# -----------------------------------------------------------------------------

print(f"Minimum observed age: {age_num.min()}")
print(f"Maximum observed age: {age_num.max()}")


# Identify invalid ages
invalid_age_mask = (
    age_num.notna()
    & ((age_num < 0) | (age_num > 105))
)

n_invalid_age = invalid_age_mask.sum()

print(f"\nInvalid Age values (<0 or >105): {n_invalid_age:,}")

if n_invalid_age > 0:
    print("\nInvalid Age value frequencies:")
    print(
        age_num.loc[invalid_age_mask]
        .value_counts()
        .sort_index()
    )


# Record originally missing ages
n_missing_age = age_num.isna().sum()

print(f"\nMissing Age values before cleaning: {n_missing_age:,}")


# -----------------------------------------------------------------------------
# Replace invalid ages with missing
# -----------------------------------------------------------------------------

age_num = age_num.mask(invalid_age_mask)


# -----------------------------------------------------------------------------
# Create harmonized Age Group
# -----------------------------------------------------------------------------

age_group = pd.Series(
    "Unknown",
    index=df.index,
    dtype="string"
)

age_group.loc[age_num.between(0, 17)] = "0 - 17"
age_group.loc[age_num.between(18, 30)] = "18 - 30"
age_group.loc[age_num.between(31, 60)] = "31 - 60"
age_group.loc[age_num.between(61, 105)] = "61+"


# -----------------------------------------------------------------------------
# Update Age and add Age Group
# -----------------------------------------------------------------------------

df["Age"] = (
    age_num
    .astype("Int64")
    .astype("string")
    .fillna("Unknown")
)

df["Age Group"] = age_group


# -----------------------------------------------------------------------------
# Validation checks
# -----------------------------------------------------------------------------

expected_age_groups = {
    "0 - 17",
    "18 - 30",
    "31 - 60",
    "61+",
    "Unknown",
}

unexpected_age_groups = (
    set(df["Age Group"].unique())
    - expected_age_groups
)

if unexpected_age_groups:
    raise ValueError(
        f"Unexpected Age Group values found: "
        f"{sorted(unexpected_age_groups)}"
    )


# Confirm that all missing and invalid ages became Unknown
expected_unknown_age = n_missing_age + n_invalid_age

assert df["Age"].eq("Unknown").sum() == expected_unknown_age, (
    "The number of Unknown Age values does not match the number of "
    "originally missing plus invalid Age values."
)

assert df["Age Group"].eq("Unknown").sum() == expected_unknown_age, (
    "The number of Unknown Age Group values does not match the number "
    "of missing plus invalid Age values."
)


# Confirm results
print("\nAge cleaning completed successfully.")
print(f"Unknown Age values: {df['Age'].eq('Unknown').sum():,}")

print("\nAge Group distribution:")
print(df["Age Group"].value_counts(dropna=False))

# =============================================================================
# HARMONIZE ANTIBIOTIC COLUMNS AND INTERPRETATION VALUES
# =============================================================================

# -----------------------------------------------------------------------------
# Define antibiotic interpretation column renaming map
# -----------------------------------------------------------------------------

interpretation_rename_map = {
    "Amikacin SIR": "Amikacin_I",
    "Cefepime SIR": "Cefepime_I",
    "Ciprofloxacin SIR": "Ciprofloxacin_I",
    "Colistin SIR": "Colistin_I",
    "Imipenem SIR": "Imipenem_I",
    "Meropenem SIR": "Meropenem_I",
    "Minocycline SIR": "Minocycline_I",
    "Sulbactum SIR": "Sulbactam_I",
    "Sulbactam/514 at 4 mcg/ml SIR":
        "Sulbactam/514 at 4 mcg/ml_I",
    "Tigecycline SIR": "Tigecycline_I",
}


# -----------------------------------------------------------------------------
# Verify expected source columns
# -----------------------------------------------------------------------------

missing_interpretation_columns = [
    col for col in interpretation_rename_map
    if col not in df.columns
]

if missing_interpretation_columns:
    raise KeyError(
        f"Expected interpretation columns not found: "
        f"{missing_interpretation_columns}"
    )


# Check for potential rename collisions
rename_collisions = [
    new_col
    for old_col, new_col in interpretation_rename_map.items()
    if new_col in df.columns and new_col != old_col
]

if rename_collisions:
    raise ValueError(
        f"Target column names already exist: {rename_collisions}"
    )


# -----------------------------------------------------------------------------
# Rename interpretation columns
# -----------------------------------------------------------------------------

df = df.rename(columns=interpretation_rename_map)


# -----------------------------------------------------------------------------
# Harmonize interpretation values
# -----------------------------------------------------------------------------

interpretation_columns = list(
    interpretation_rename_map.values()
)

interpretation_value_map = {
    "S": "Susceptible",
    "I": "Susceptible",
    "R": "Resistant",
}


for col in interpretation_columns:

    # Standardize formatting while preserving missing values
    cleaned_values = (
        df[col]
        .astype("string")
        .str.strip()
        .str.upper()
        .replace("", pd.NA)
    )

    # Check for unexpected source values
    unexpected_values = (
        set(cleaned_values.dropna().unique())
        - set(interpretation_value_map.keys())
    )

    if unexpected_values:
        raise ValueError(
            f"Unexpected interpretation values found in {col}: "
            f"{sorted(unexpected_values)}"
        )

    # Map S/I/R values to ATLAS-compatible labels
    df[col] = cleaned_values.map(
        interpretation_value_map
    )


# -----------------------------------------------------------------------------
# Validate harmonized antibiotic column structure
# -----------------------------------------------------------------------------

mic_columns = [
    "Amikacin",
    "Cefepime",
    "Ciprofloxacin",
    "Colistin",
    "Imipenem",
    "Meropenem",
    "Minocycline",
    "Sulbactam",
    "Sulbactam/514 at 4 mcg/ml",
    "Tigecycline",
]


# Confirm that each MIC column has a paired interpretation column
missing_pairs = [
    mic_col
    for mic_col in mic_columns
    if f"{mic_col}_I" not in df.columns
]

if missing_pairs:
    raise ValueError(
        f"MIC columns missing paired interpretation columns: "
        f"{missing_pairs}"
    )


# Confirm interpretation values after harmonization
expected_interpretation_values = {
    "Susceptible",
    "Resistant",
}

for col in interpretation_columns:

    unexpected_values = (
        set(df[col].dropna().unique())
        - expected_interpretation_values
    )

    if unexpected_values:
        raise ValueError(
            f"Unexpected harmonized values found in {col}: "
            f"{sorted(unexpected_values)}"
        )


# -----------------------------------------------------------------------------
# Confirm results
# -----------------------------------------------------------------------------

print(
    "Antibiotic column and interpretation harmonization "
    "completed successfully."
)

print("\nMIC and interpretation column pairs:")

for mic_col in mic_columns:
    print(f"{mic_col}  |  {mic_col}_I")


print("\nInterpretation value distributions:")

for col in interpretation_columns:
    print(f"\n{col}")
    print(df[col].value_counts(dropna=False))

# =============================================================================
# CREATE HARMONIZED SOURCE VARIABLE
# =============================================================================

# Preserve the original BodyLocation column unchanged.
# Create a new Source column using explicit mappings to ATLAS terminology.

source_map = {
    # Bodily fluids
    "Bodily Fluids: Abdominal": "Abdominal Fluid",
    "Bodily Fluids: Abscess / Pus": "Abscess",
    "Bodily Fluids: Aspirate": "Aspirate",
    "Bodily Fluids: Bile": "Bile",
    "Bodily Fluids: Peritoneal": "Peritoneal Fluid",
    "Bodily Fluids: Pleural": "Pleural Fluid",
    "Bodily Fluids: Thoracentesis": "Thoracentesis Fluid",
    "Bodily Fluids: Tissue": "Tissue Fluid",

    # Central nervous system and cardiovascular system
    "CNS: Spinal Cord": "Spinal Cord",
    "CVS: Blood": "Blood",

    # Gastrointestinal
    "GI: Abscess": "Abscess",
    "GI: Appendix": "Appendix",
    "GI: Diverticulum": "Diverticulum",
    "GI: Gall Bladder": "Gall Bladder",
    "GI: Large Colon": "Colon",
    "GI: Liver": "Liver",
    "GI: Other": "Intestinal: Other",
    "GI: Pancreas": "Pancreas",
    "GI: Small Colon": "Colon",
    "GI: Stomach": "Stomach",

    # Genitourinary
    "GU: Kidneys": "Kidney",
    "GU: Other": "Genitourinary: Other",
    "GU: Ureter": "Ureter",
    "GU: Urethra": "Urethra",
    "GU: Urinary Bladder": "Bladder",
    "GU: Urine": "Urine",
    "Genital/Urinary (GU)": "Genitourinary: Other",

    # Head, eyes, ears, nose, and throat
    "HEENT: Eyes": "Eye",

    # Integumentary
    "INT: Abscess": "Abscess",
    "INT: Burn": "Burn",
    "INT: Cellulitis/Erysipelas": "Cellulitis",
    "INT: Decubitus": "Decubitus",
    "INT: Furuncle": "Furuncle",
    "INT: Impetiginous lesions": "Impetiginous lesions",
    "INT: Other": "Skin: Other",
    "INT: Skin Ulcer": "Ulcer",
    "INT: Wound": "Wound",

    # Respiratory
    "RTI: Sputum": "Sputum",
    "Respiratory": "Respiratory: Other",
    "Respiratory: Bronchial brushing": "Bronchus",
    "Respiratory: Bronchials": "Bronchus",
    "Respiratory: Bronchoalveolar lavage":
        "Bronchoalveolar lavage",
    "Respiratory: Endotracheal aspirate":
        "Endotracheal aspirate",
    "Respiratory: Lungs": "Lungs",
    "Respiratory: Other": "Respiratory: Other",
    "Respiratory: Sinuses": "Respiratory: Sinuses",
    "Respiratory: Sputum": "Sputum",
    "Respiratory: Trachea": "Trachea",

    # Unspecified
    "Unknown": "None Given",
}


# -----------------------------------------------------------------------------
# Prepare BodyLocation values for mapping
# -----------------------------------------------------------------------------

body_location_clean = (
    df["BodyLocation"]
    .astype("string")
    .str.strip()
    .replace("", pd.NA)
)


# -----------------------------------------------------------------------------
# Validate that all observed values have an explicit mapping
# -----------------------------------------------------------------------------

unmapped_body_locations = (
    set(body_location_clean.dropna().unique())
    - set(source_map.keys())
)

if unmapped_body_locations:
    raise ValueError(
        f"Unmapped BodyLocation values found: "
        f"{sorted(unmapped_body_locations)}"
    )


# -----------------------------------------------------------------------------
# Create harmonized Source variable
# -----------------------------------------------------------------------------

df["Source"] = (
    body_location_clean
    .map(source_map)
    .fillna("None Given")
)


# -----------------------------------------------------------------------------
# Validation checks
# -----------------------------------------------------------------------------

assert "BodyLocation" in df.columns, (
    "Original BodyLocation column was not preserved."
)

assert df["Source"].notna().all(), (
    "Missing values remain in the harmonized Source column."
)


# Confirm that resulting Source values are expected ATLAS-aligned values
expected_source_values = (
    set(source_map.values())
    | {"None Given"}
)

unexpected_source_values = (
    set(df["Source"].unique())
    - expected_source_values
)

if unexpected_source_values:
    raise ValueError(
        f"Unexpected values found in Source: "
        f"{sorted(unexpected_source_values)}"
    )


# -----------------------------------------------------------------------------
# Confirm results
# -----------------------------------------------------------------------------

print("Source harmonization completed successfully.")
print(f"Unique BodyLocation values: {df['BodyLocation'].nunique(dropna=True)}")
print(f"Unique harmonized Source values: {df['Source'].nunique(dropna=True)}")

print("\nHarmonized Source distribution:")
print(df["Source"].value_counts(dropna=False))

# =============================================================================
# CREATE HARMONIZED SPECIALITY VARIABLE
# =============================================================================

# Preserve the original FacilityName column unchanged.
# Create a new Speciality column using explicit mappings to ATLAS terminology.

speciality_map = {
    "Clinic": "Clinic / Office",
    "Clinic / Office": "Clinic / Office",
    "Emergency Room": "Emergency Room",
    "General Unspecified ICU": "General Unspecified ICU",
    "Medicine General": "Medicine General",
    "Medicine ICU": "Medicine ICU",
    "None Given": "None Given",
    "Nursing Home / Rehab": "Nursing Home / Rehab",
    "Office": "Clinic / Office",
    "Other": "Other",
    "Pediatric General": "Pediatric General",
    "Pediatric ICU": "Pediatric ICU",
    "Surgery General": "Surgery General",
    "Surgery ICU": "Surgery ICU",
}


# -----------------------------------------------------------------------------
# Prepare FacilityName values for mapping
# -----------------------------------------------------------------------------

facility_clean = (
    df["FacilityName"]
    .astype("string")
    .str.strip()
    .replace("", pd.NA)
)


# -----------------------------------------------------------------------------
# Validate that all observed non-missing values have an explicit mapping
# -----------------------------------------------------------------------------

unmapped_facility_values = (
    set(facility_clean.dropna().unique())
    - set(speciality_map.keys())
)

if unmapped_facility_values:
    raise ValueError(
        f"Unmapped FacilityName values found: "
        f"{sorted(unmapped_facility_values)}"
    )


# -----------------------------------------------------------------------------
# Create harmonized Speciality variable
# -----------------------------------------------------------------------------

df["Speciality"] = facility_clean.map(speciality_map)


# -----------------------------------------------------------------------------
# Validation checks
# -----------------------------------------------------------------------------

# Confirm that the original source column was preserved
assert "FacilityName" in df.columns, (
    "Original FacilityName column was not preserved."
)


# Define valid ATLAS Speciality categories
expected_speciality_values = {
    "Clinic / Office",
    "Emergency Room",
    "General Unspecified ICU",
    "Medicine General",
    "Medicine ICU",
    "None Given",
    "Nursing Home / Rehab",
    "Other",
    "Pediatric General",
    "Pediatric ICU",
    "Surgery General",
    "Surgery ICU",
}


# Confirm resulting non-missing values align with ATLAS categories
unexpected_speciality_values = (
    set(df["Speciality"].dropna().unique())
    - expected_speciality_values
)

if unexpected_speciality_values:
    raise ValueError(
        f"Unexpected values found in Speciality: "
        f"{sorted(unexpected_speciality_values)}"
    )


# -----------------------------------------------------------------------------
# Confirm results
# -----------------------------------------------------------------------------

print("Speciality harmonization completed successfully.")
print(f"Unique FacilityName values: {df['FacilityName'].nunique(dropna=True)}")
print(f"Unique Speciality values: {df['Speciality'].nunique(dropna=True)}")
print(f"Missing Speciality values: {df['Speciality'].isna().sum():,}")

print("\nHarmonized Speciality distribution:")
print(df["Speciality"].value_counts(dropna=False))

# =============================================================================
# SAVE HARMONIZED ACINETOBACTER DATASET
# =============================================================================

# -----------------------------------------------------------------------------
# Validate the final dataset dimensions
# -----------------------------------------------------------------------------

# Harmonization adds four columns without changing the number of rows:
# Source Database, Age Group, Source, and Speciality.
expected_shape = (
    original_shape[0],
    original_shape[1] + 4,
)

if df.shape != expected_shape:
    raise ValueError(
        "Unexpected dimensions after Acinetobacter harmonization. "
        f"Expected {expected_shape}, found {df.shape}."
    )


# -----------------------------------------------------------------------------
# Define the output directory and files
# -----------------------------------------------------------------------------

output_dir = project_dir / "Cleaned"
output_dir.mkdir(parents=True, exist_ok=True)

output_parquet = output_dir / "Acinetobacter_harmonized.parquet"
output_csv = output_dir / "Acinetobacter_harmonized.csv"


# -----------------------------------------------------------------------------
# Save the harmonized dataset
# -----------------------------------------------------------------------------

df.to_parquet(
    output_parquet,
    index=False,
)

df.to_csv(
    output_csv,
    index=False,
)


# -----------------------------------------------------------------------------
# Validate the exported files
# -----------------------------------------------------------------------------

for output_file in (output_parquet, output_csv):
    if not output_file.is_file() or output_file.stat().st_size == 0:
        raise OSError(
            f"Output file was not created successfully: {output_file}"
        )


# -----------------------------------------------------------------------------
# Confirm successful export
# -----------------------------------------------------------------------------

print("Harmonized Acinetobacter dataset saved successfully.")
print(f"Rows: {df.shape[0]:,}")
print(f"Columns: {df.shape[1]:,}")
print(f"Parquet: {output_parquet}")
print(f"CSV:     {output_csv}")

print("\nFile sizes:")
print(
    f"Parquet: "
    f"{output_parquet.stat().st_size / (1024**2):,.1f} MB"
)
print(
    f"CSV:     "
    f"{output_csv.stat().st_size / (1024**2):,.1f} MB"
)