# -*- coding: utf-8 -*-
"""03_clean_keystone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zLw9CEd89Y5Npp3K_iHpKRg7r3TnnrkC
"""

# =============================================================================
# SETUP AND DATA IMPORT
# =============================================================================

from pathlib import Path

import pandas as pd


# -----------------------------------------------------------------------------
# Configure the project directory
# -----------------------------------------------------------------------------

try:
    from google.colab import drive
except ImportError:
    drive = None


if drive is not None:
    # Google Colab: mount Drive and use the existing project location.
    drive.mount("/content/drive")

    project_dir = Path(
        "/content/drive/MyDrive/AMR Data Challenge 2026/"
        "Harmonized Database Creation"
    )
else:
    # Local execution: start the notebook from the project directory.
    project_dir = Path.cwd()


# -----------------------------------------------------------------------------
# Define and validate the input file
# -----------------------------------------------------------------------------

input_file = project_dir / "Raw" / "Keystone.xlsx"

if not input_file.is_file():
    raise FileNotFoundError(
        "KEYSTONE input file not found. "
        f"Expected location: {input_file}"
    )


# -----------------------------------------------------------------------------
# Load the raw KEYSTONE dataset
# -----------------------------------------------------------------------------

df = pd.read_excel(input_file)


# Store the original dimensions for final validation
original_shape = df.shape


# -----------------------------------------------------------------------------
# Confirm successful import
# -----------------------------------------------------------------------------

print("KEYSTONE dataset loaded successfully.")
print(f"Rows: {df.shape[0]:,}")
print(f"Columns: {df.shape[1]:,}")
print(f"Input: {input_file}")

# =============================================================================
# VALIDATE COLUMN NAMES
# =============================================================================

# Confirm that all column names are unique
duplicated_columns = (
    df.columns[df.columns.duplicated()]
    .tolist()
)

if duplicated_columns:
    raise ValueError(
        f"Duplicated column names found: {duplicated_columns}"
    )


# Confirm that no embedded line breaks remain
columns_with_linebreaks = [
    col for col in df.columns
    if "\n" in str(col) or "\r" in str(col)
]

if columns_with_linebreaks:
    raise ValueError(
        "Column names containing embedded line breaks were found: "
        f"{columns_with_linebreaks}"
    )


# Confirm that no column names have leading or trailing whitespace
columns_with_outer_whitespace = [
    col for col in df.columns
    if str(col) != str(col).strip()
]

if columns_with_outer_whitespace:
    raise ValueError(
        "Column names containing leading or trailing whitespace were found: "
        f"{columns_with_outer_whitespace}"
    )


print("Column name validation completed.")
print(f"Unique columns confirmed: {df.shape[1]:,}")
print("No embedded line breaks found.")
print("No leading or trailing column-name whitespace found.")

# =============================================================================
# HARMONIZE CORE IDENTIFIER AND YEAR COLUMNS
# =============================================================================

# Define confirmed column renaming map
metadata_rename_map = {
    "Collection Number": "Isolate Id",
    "Study Year": "Year",
}


# Verify that all expected source columns are present
missing_columns = [
    col for col in metadata_rename_map
    if col not in df.columns
]

if missing_columns:
    raise KeyError(
        f"Expected columns not found: {missing_columns}"
    )


# Rename columns
df = df.rename(columns=metadata_rename_map)


# Add dataset provenance column
df["Source Database"] = "Keystone"


# Validate changes
assert "Isolate Id" in df.columns
assert "Year" in df.columns
assert df["Source Database"].eq("Keystone").all()


print("Core metadata harmonization completed.")
print(f"Rows: {df.shape[0]:,}")
print(f"Unique Source Database values: {df['Source Database'].unique()}")

# =============================================================================
# HARMONIZE COUNTRY VALUES
# =============================================================================

# Define confirmed KEYSTONE-to-ATLAS country mappings
country_map = {
    "UK": "United Kingdom",
    "USA": "United States",
}


# Harmonize confirmed country name differences
df["Country"] = df["Country"].replace(country_map)


# Validate that source values were fully replaced
remaining_unharmonized = set(df["Country"].dropna().unique()) & set(country_map)

assert not remaining_unharmonized, (
    f"Unharmonized country values remain: {remaining_unharmonized}"
)


# Confirm resulting country values
print("Country harmonization completed.")
print(sorted(df["Country"].dropna().unique()))

# =============================================================================
# HARMONIZE GENDER VALUES
# =============================================================================

# Clean surrounding whitespace
gender_clean = (
    df["Gender"]
    .astype("string")
    .str.strip()
)


# Verify that all non-missing values are expected
expected_gender_values = {"M", "F"}

unexpected_gender_values = (
    set(gender_clean.dropna().unique())
    - expected_gender_values
)

if unexpected_gender_values:
    raise ValueError(
        f"Unexpected Gender values found: "
        f"{sorted(unexpected_gender_values)}"
    )


# Define confirmed gender mappings
gender_map = {
    "M": "Male",
    "F": "Female",
}


# Harmonize Gender values and classify missing values as Unknown
df["Gender"] = (
    gender_clean
    .map(gender_map)
    .fillna("Unknown")
)


# Confirm resulting values
print("Gender harmonization completed.")
print(df["Gender"].value_counts(dropna=False))

# =============================================================================
# CLEAN AGE AND CREATE AGE GROUP
# =============================================================================

# Convert Age to numeric for validation
age_num = pd.to_numeric(
    df["Age"],
    errors="coerce"
)


# Count original missing and invalid values
n_missing = df["Age"].isna().sum()
n_below_0 = age_num.lt(0).sum()
n_above_105 = age_num.gt(105).sum()


# Report age issues before cleaning
print("Age checks before cleaning:")
print(f"Missing values: {n_missing:,}")
print(f"Values below 0: {n_below_0:,}")
print(f"Values above 105: {n_above_105:,}")


# Retain only valid ages from 0 to 105
age_clean = age_num.where(
    age_num.between(0, 105)
)


# Create harmonized Age Group variable
age_group = pd.Series(
    "Unknown",
    index=df.index,
    dtype="string"
)

age_group.loc[age_clean.between(0, 17)] = "0 - 17"
age_group.loc[age_clean.between(18, 30)] = "18 - 30"
age_group.loc[age_clean.between(31, 60)] = "31 - 60"
age_group.loc[age_clean.between(61, 105)] = "61+"


# Replace invalid or missing Age values with Unknown
df["Age"] = (
    age_clean
    .astype("string")
    .str.replace(r"\.0$", "", regex=True)
    .fillna("Unknown")
)


# Add harmonized Age Group column
df["Age Group"] = age_group


# Validate results
age_check = pd.to_numeric(
    df["Age"],
    errors="coerce"
)

assert age_check.dropna().between(0, 105).all()

expected_age_groups = {
    "0 - 17",
    "18 - 30",
    "31 - 60",
    "61+",
    "Unknown",
}

assert set(df["Age Group"].unique()).issubset(expected_age_groups)


# Confirm results
print("\nAge cleaning completed.")
print(f"Unknown ages: {df['Age'].eq('Unknown').sum():,}")

print("\nAge Group distribution:")
print(df["Age Group"].value_counts(dropna=False))

# =============================================================================
# HARMONIZE ANTIBIOTIC AND INTERPRETATION COLUMN NAMES
# =============================================================================

# Define the complete set of antibiotic names in the source KEYSTONE file
source_keystone_antibiotics = [
    "Omadacycline",
    "Doxycycline",
    "Minocycline",
    "Tetracycline",
    "Tigecycline",
    "Oxacillin",
    "Ceftaroline",
    "Ceftriaxone",
    "Amoxicillin- clavulanic acid",
    "Piperacillin- tazobactam",
    "Levofloxacin",
    "Erythromycin",
    "Clindamycin",
    "Linezolid",
    "Daptomycin",
    "Vancomycin",
    "Teicoplanin",
    "Gentamicin",
    "Amikacin",
    "Ampicillin",
    "Azithromycin",
    "Aztreonam",
    "Cefepime",
    "Ceftazidime",
    "Colistin",
    "Imipenem",
    "Moxifloxacin",
    "Penicillin",
    "Trimethoprim- sulfamethoxazole",
]


# Define confirmed KEYSTONE-to-ATLAS antibiotic name mappings
antibiotic_name_map = {
    "Amoxicillin- clavulanic acid": "Amoxycillin clavulanate",
    "Piperacillin- tazobactam": "Piperacillin tazobactam",
    "Trimethoprim- sulfamethoxazole": "Trimethoprim sulfa",
}


# Verify that every expected MIC and _SIR column is present
expected_source_columns = []

for antibiotic in source_keystone_antibiotics:
    expected_source_columns.extend([
        antibiotic,
        f"{antibiotic}_SIR",
    ])

missing_antibiotic_columns = [
    col for col in expected_source_columns
    if col not in df.columns
]

if missing_antibiotic_columns:
    raise KeyError(
        "Expected KEYSTONE antibiotic columns not found: "
        f"{missing_antibiotic_columns}"
    )


# Identify any unexpected _SIR columns before renaming
expected_sir_columns = {
    f"{antibiotic}_SIR"
    for antibiotic in source_keystone_antibiotics
}

observed_sir_columns = {
    col for col in df.columns
    if col.endswith("_SIR")
}

unexpected_sir_columns = (
    observed_sir_columns
    - expected_sir_columns
)

if unexpected_sir_columns:
    raise ValueError(
        "Unexpected _SIR columns found: "
        f"{sorted(unexpected_sir_columns)}"
    )


# Build a combined renaming map for MIC and interpretation columns
antibiotic_column_rename_map = {}

for source_name in source_keystone_antibiotics:
    harmonized_name = antibiotic_name_map.get(
        source_name,
        source_name
    )

    # Rename MIC column where required
    antibiotic_column_rename_map[source_name] = harmonized_name

    # Rename _SIR to _I and harmonize its antibiotic name
    antibiotic_column_rename_map[
        f"{source_name}_SIR"
    ] = f"{harmonized_name}_I"


# Apply antibiotic and interpretation column renaming
df = df.rename(
    columns=antibiotic_column_rename_map
)


# Define final harmonized KEYSTONE antibiotic names
keystone_antibiotics = [
    antibiotic_name_map.get(
        antibiotic,
        antibiotic
    )
    for antibiotic in source_keystone_antibiotics
]

interpretation_columns = [
    f"{antibiotic}_I"
    for antibiotic in keystone_antibiotics
]


# Validate the resulting column structure
if not df.columns.is_unique:
    duplicated_columns = (
        df.columns[df.columns.duplicated()]
        .tolist()
    )

    raise ValueError(
        "Duplicate column names created during antibiotic harmonization: "
        f"{duplicated_columns}"
    )

remaining_sir_columns = [
    col for col in df.columns
    if col.endswith("_SIR")
]

assert not remaining_sir_columns, (
    f"Unharmonized _SIR columns remain: {remaining_sir_columns}"
)

missing_mic_columns = [
    col for col in keystone_antibiotics
    if col not in df.columns
]

missing_interpretation_columns = [
    col for col in interpretation_columns
    if col not in df.columns
]

if missing_mic_columns:
    raise KeyError(
        f"Harmonized MIC columns missing: {missing_mic_columns}"
    )

if missing_interpretation_columns:
    raise KeyError(
        "Harmonized interpretation columns missing: "
        f"{missing_interpretation_columns}"
    )


# Reorder columns so each _I column follows its corresponding MIC column
interpretation_column_set = set(interpretation_columns)

column_order = []

for col in df.columns:

    if col in interpretation_column_set:
        continue

    column_order.append(col)

    if col in keystone_antibiotics:
        column_order.append(f"{col}_I")


df = df[column_order]


print("Antibiotic column-name harmonization completed.")
print(f"MIC columns confirmed: {len(keystone_antibiotics)}")
print(
    "Interpretation columns renamed from _SIR to _I: "
    f"{len(interpretation_columns)}"
)

print("\nAntibiotic names harmonized to ATLAS:")
for source_name, harmonized_name in antibiotic_name_map.items():
    print(f"{source_name} → {harmonized_name}")

# =============================================================================
# HARMONIZE ANTIMICROBIAL INTERPRETATION VALUES
# =============================================================================

# Store interpretation columns using pandas string dtype
interpretation_data = (
    df[interpretation_columns]
    .astype("string")
)


# Standardize surrounding whitespace and capitalization
interpretation_data = interpretation_data.apply(
    lambda column: column.str.strip().str.upper()
)


# Identify all non-missing source interpretation values
observed_interpretation_values = {
    value
    for col in interpretation_columns
    for value in interpretation_data[col].dropna().unique()
}

expected_interpretation_values = {
    "S",
    "I",
    "R",
}

unexpected_interpretation_values = (
    observed_interpretation_values
    - expected_interpretation_values
)

if unexpected_interpretation_values:
    raise ValueError(
        "Unexpected antimicrobial interpretation values found: "
        f"{sorted(unexpected_interpretation_values)}"
    )


# Count source values before recoding
n_s_before = int(
    interpretation_data.eq("S").sum().sum()
)

n_i_before = int(
    interpretation_data.eq("I").sum().sum()
)

n_r_before = int(
    interpretation_data.eq("R").sum().sum()
)

n_missing_before = int(
    interpretation_data.isna().sum().sum()
)


# Recode S and I as Susceptible and R as Resistant
interpretation_value_map = {
    "S": "Susceptible",
    "I": "Susceptible",
    "R": "Resistant",
}

df[interpretation_columns] = (
    interpretation_data
    .replace(interpretation_value_map)
)


# Validate final interpretation values
final_interpretation_values = {
    value
    for col in interpretation_columns
    for value in df[col].dropna().unique()
}

expected_final_values = {
    "Susceptible",
    "Resistant",
}

unexpected_final_values = (
    final_interpretation_values
    - expected_final_values
)

if unexpected_final_values:
    raise ValueError(
        "Unexpected harmonized interpretation values found: "
        f"{sorted(unexpected_final_values)}"
    )


# Confirm that the recoding produced the expected totals
n_susceptible_after = int(
    df[interpretation_columns]
    .eq("Susceptible")
    .sum()
    .sum()
)

n_resistant_after = int(
    df[interpretation_columns]
    .eq("Resistant")
    .sum()
    .sum()
)

n_missing_after = int(
    df[interpretation_columns]
    .isna()
    .sum()
    .sum()
)

assert n_susceptible_after == n_s_before + n_i_before
assert n_resistant_after == n_r_before
assert n_missing_after == n_missing_before

assert not (
    df[interpretation_columns]
    .isin(["S", "I", "R", "Intermediate"])
    .any()
    .any()
)


# Report interpretation-value changes
print("Antimicrobial interpretation harmonization completed.")
print(f"Original S values: {n_s_before:,}")
print(f"Original I values: {n_i_before:,}")
print(f"Original R values: {n_r_before:,}")
print(f"Missing interpretation values retained: {n_missing_before:,}")

print("\nFinal interpretation totals:")
print(f"Susceptible: {n_susceptible_after:,}")
print(f"Resistant:   {n_resistant_after:,}")

# =============================================================================
# HARMONIZE SOURCE VARIABLE
# =============================================================================

# Preserve original KEYSTONE source variables
df = df.rename(
    columns={
        "Specimen Type": "Specimen Type_Orig",
        "Infection Source": "Infection Source_Orig",
    }
)


# Create harmonized Source variable from KEYSTONE Specimen Type
df["Source"] = df["Specimen Type_Orig"].copy()


# Define confirmed KEYSTONE-to-ATLAS source mappings
source_map = {
    "Abscess (pus)": "Abscess",
    "Ascitic fluid": "Ascetic Fluid",
    "Aspirate": "Aspirate",
    "Blood culture": "Blood",
    "Bronchoalveolar lavage/wash": "Bronchoalveolar lavage",
    "Catheter": "Catheters",
    "Catheter tip": "Catheters",
    "Cerebrospinal fluid": "CSF",
    "Eye/conjunctiva": "Eye",
    "Middle ear fluid": "Ear",
    "Peritoneal fluid": "Peritoneal Fluid",
    "Plueral fluid": "Pleural Fluid",
    "Rectum/Rectal Swab": "Rectum",
    "Sinus": "Respiratory: Sinuses",
    "Sputum": "Sputum",
    "Ureteral Catheter": "Catheters",
    "Ureteral catheter": "Catheters",
    "Urethral catheter (Foley)": "Catheters",
    "Urine/Urinary tract": "Urine",
}


# Apply confirmed mappings
df["Source"] = df["Source"].replace(source_map)


# Replace missing source values with Unknown
df["Source"] = df["Source"].fillna("Unknown")


# Validate preservation of original columns
assert "Specimen Type_Orig" in df.columns
assert "Infection Source_Orig" in df.columns
assert df["Source"].isna().sum() == 0


# Confirm resulting values
print("Source harmonization completed.")
print(f"Original specimen categories: {df['Specimen Type_Orig'].nunique(dropna=True)}")
print(f"Harmonized Source categories: {df['Source'].nunique(dropna=True)}")

print("\nFinal Source values:")
print(sorted(df["Source"].unique()))

# =============================================================================
# CREATE HARMONIZED SPECIALITY VARIABLE
# =============================================================================

# Define expected KEYSTONE Medical Service categories
expected_medical_services = {
    "Ambulatory/Outpatient",
    "Burn",
    "Cardiothoracic/Pulmonary",
    "Critical Care Unit",
    "Dermatology",
    "Dialysis",
    "Ear, Nose, Throat",
    "Emergency",
    "Family Practice",
    "General/GI",
    "Geriatics",
    "Hematology/Oncology",
    "Infectious Disease",
    "Intensive Care Unit",
    "Internal Medicine",
    "Long Term Care",
    "Neurology",
    "Neurosurgery",
    "Obstetrics/Gynecology",
    "Ophthalmology",
    "Orthopedics",
    "Pediatrics/Neonate",
    "Psychiatry",
    "Rehabilitation",
    "Renal",
    "Surgery",
    "Transplant",
    "Trauma",
    "Urology/Prostate",
}


# Check for unexpected non-missing values before mapping
unexpected_services = (
    set(df["Medical Service"].dropna().unique())
    - expected_medical_services
)

if unexpected_services:
    raise ValueError(
        f"Unexpected Medical Service values found: "
        f"{sorted(unexpected_services)}"
    )


# Define confirmed KEYSTONE-to-ATLAS speciality mappings
speciality_map = {
    "Ambulatory/Outpatient": "Clinic / Office",

    "Critical Care Unit": "General Unspecified ICU",
    "Intensive Care Unit": "General Unspecified ICU",

    "Emergency": "Emergency Room",

    "Dialysis": "Medicine General",
    "Family Practice": "Medicine General",
    "General/GI": "Medicine General",
    "Geriatics": "Medicine General",
    "Hematology/Oncology": "Medicine General",
    "Infectious Disease": "Medicine General",
    "Internal Medicine": "Medicine General",
    "Neurology": "Medicine General",
    "Renal": "Medicine General",

    "Long Term Care": "Nursing Home / Rehab",
    "Rehabilitation": "Nursing Home / Rehab",

    "Pediatrics/Neonate": "Pediatric General",

    "Neurosurgery": "Surgery General",
    "Orthopedics": "Surgery General",
    "Surgery": "Surgery General",
    "Trauma": "Surgery General",
    "Urology/Prostate": "Surgery General",

    "Burn": "Other",
    "Cardiothoracic/Pulmonary": "Other",
    "Dermatology": "Other",
    "Ear, Nose, Throat": "Other",
    "Obstetrics/Gynecology": "Other",
    "Ophthalmology": "Other",
    "Psychiatry": "Other",
    "Transplant": "Other",
}


# Create harmonized Speciality variable
df["Speciality"] = (
    df["Medical Service"]
    .map(speciality_map)
    .fillna("None Given")
)


# Define valid ATLAS Speciality categories
valid_specialties = {
    "Clinic / Office",
    "Emergency Room",
    "General Unspecified ICU",
    "Medicine General",
    "Medicine ICU",
    "None Given",
    "Nursing Home / Rehab",
    "Other",
    "Pediatric General",
    "Pediatric ICU",
    "Surgery General",
    "Surgery ICU",
}


# Validate resulting categories
unexpected_specialties = (
    set(df["Speciality"].unique())
    - valid_specialties
)

assert not unexpected_specialties, (
    f"Unexpected Speciality values found: {unexpected_specialties}"
)


# Confirm results
print("Speciality harmonization completed.")

print("\nHarmonized Speciality distribution:")
print(df["Speciality"].value_counts(dropna=False))

# =============================================================================
# STANDARDIZE MIC COLUMN STORAGE TYPES FOR EXPORT
# =============================================================================

# Confirm that all expected MIC columns are present
missing_mic_columns = [
    col for col in keystone_antibiotics
    if col not in df.columns
]

if missing_mic_columns:
    raise KeyError(
        f"Expected MIC columns not found: {missing_mic_columns}"
    )


# Store MIC columns as strings to preserve values and censoring symbols
for col in keystone_antibiotics:
    df[col] = df[col].astype("string")


# Validate MIC column types
non_string_mic_columns = [
    col for col in keystone_antibiotics
    if not isinstance(df[col].dtype, pd.StringDtype)
]

if non_string_mic_columns:
    raise TypeError(
        f"MIC columns not stored as string: {non_string_mic_columns}"
    )


print("MIC storage type standardization completed.")
print(f"MIC columns converted to string: {len(keystone_antibiotics)}")
print("Censoring symbols and missing values preserved.")

# =============================================================================
# SAVE HARMONIZED KEYSTONE DATASET
# =============================================================================

# -----------------------------------------------------------------------------
# Validate the final dataset dimensions
# -----------------------------------------------------------------------------

# Harmonization adds four columns without changing the number of rows:
# Source Database, Age Group, Source, and Speciality.
expected_shape = (
    original_shape[0],
    original_shape[1] + 4,
)

if df.shape != expected_shape:
    raise ValueError(
        "Unexpected dimensions after KEYSTONE harmonization. "
        f"Expected {expected_shape}, found {df.shape}."
    )


# -----------------------------------------------------------------------------
# Define the output directory and files
# -----------------------------------------------------------------------------

output_dir = project_dir / "Cleaned"
output_dir.mkdir(parents=True, exist_ok=True)

output_parquet = output_dir / "Keystone_harmonized.parquet"
output_csv = output_dir / "Keystone_harmonized.csv"


# -----------------------------------------------------------------------------
# Save the harmonized dataset
# -----------------------------------------------------------------------------

df.to_parquet(
    output_parquet,
    index=False,
)

df.to_csv(
    output_csv,
    index=False,
)


# -----------------------------------------------------------------------------
# Validate the exported files
# -----------------------------------------------------------------------------

for output_file in (output_parquet, output_csv):
    if not output_file.is_file() or output_file.stat().st_size == 0:
        raise OSError(
            f"Output file was not created successfully: {output_file}"
        )


# -----------------------------------------------------------------------------
# Confirm successful export
# -----------------------------------------------------------------------------

print("Harmonized KEYSTONE dataset saved successfully.")
print(f"Rows: {df.shape[0]:,}")
print(f"Columns: {df.shape[1]:,}")
print(f"Parquet: {output_parquet}")
print(f"CSV:     {output_csv}")

print("\nFile sizes:")
print(
    f"Parquet: "
    f"{output_parquet.stat().st_size / (1024**2):,.1f} MB"
)
print(
    f"CSV:     "
    f"{output_csv.stat().st_size / (1024**2):,.1f} MB"
)