# -*- coding: utf-8 -*-
"""04_Initial_combination.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k6Fgp59PGxT2FEYnKmxMe-qGQnkHk4Q1
"""

# =============================================================================
# SETUP AND INPUT FILE PATHS
# =============================================================================

from pathlib import Path

import pandas as pd


# -----------------------------------------------------------------------------
# Configure the project directory
# -----------------------------------------------------------------------------

try:
    from google.colab import drive
except ImportError:
    drive = None


if drive is not None:
    # Google Colab: mount Drive and use the existing project location.
    drive.mount("/content/drive")

    project_dir = Path(
        "/content/drive/MyDrive/AMR Data Challenge 2026/"
        "Harmonized Database Creation"
    )
else:
    # Local execution: start the notebook from the project directory.
    project_dir = Path.cwd()


# -----------------------------------------------------------------------------
# Define the cleaned-data directory
# -----------------------------------------------------------------------------

cleaned_dir = project_dir / "Cleaned"


# -----------------------------------------------------------------------------
# Define the three input files
# -----------------------------------------------------------------------------

atlas_file = cleaned_dir / "Atlas_harmonized.csv"
keystone_file = cleaned_dir / "Keystone_harmonized.csv"
acinetobacter_file = cleaned_dir / "Acinetobacter_harmonized.csv"


# -----------------------------------------------------------------------------
# Confirm that all input files exist
# -----------------------------------------------------------------------------

input_files = [
    atlas_file,
    keystone_file,
    acinetobacter_file,
]

for input_file in input_files:
    if not input_file.exists():
        raise FileNotFoundError(
            f"Input file not found: {input_file}"
        )


print("All three harmonized input files found successfully.")

# =============================================================================
# LOAD HARMONIZED DATASETS
# =============================================================================

atlas = pd.read_csv(
    atlas_file,
    low_memory=False
)

keystone = pd.read_csv(
    keystone_file,
    low_memory=False
)

acinetobacter = pd.read_csv(
    acinetobacter_file,
    low_memory=False
)


# Confirm successful loading
print("ATLAS:")
print(f"Rows: {atlas.shape[0]:,}")
print(f"Columns: {atlas.shape[1]:,}")

print("\nKEYSTONE:")
print(f"Rows: {keystone.shape[0]:,}")
print(f"Columns: {keystone.shape[1]:,}")

print("\nACINETOBACTER:")
print(f"Rows: {acinetobacter.shape[0]:,}")
print(f"Columns: {acinetobacter.shape[1]:,}")

# =============================================================================
# REVIEW DATABASE-SPECIFIC AND SHARED COLUMNS
# =============================================================================

# Convert column names to sets
atlas_cols = set(atlas.columns)
keystone_cols = set(keystone.columns)
acinetobacter_cols = set(acinetobacter.columns)


# -----------------------------------------------------------------------------
# Columns shared by all three datasets
# -----------------------------------------------------------------------------

common_columns = sorted(
    atlas_cols
    & keystone_cols
    & acinetobacter_cols
)


# -----------------------------------------------------------------------------
# Columns unique to each dataset
# -----------------------------------------------------------------------------

atlas_only = sorted(
    atlas_cols
    - keystone_cols
    - acinetobacter_cols
)

keystone_only = sorted(
    keystone_cols
    - atlas_cols
    - acinetobacter_cols
)

acinetobacter_only = sorted(
    acinetobacter_cols
    - atlas_cols
    - keystone_cols
)


# -----------------------------------------------------------------------------
# Display results
# -----------------------------------------------------------------------------

print(
    f"Columns shared by all 3 datasets: "
    f"{len(common_columns):,}"
)

print("\nATLAS-only columns:")
print(atlas_only)

print("\nKEYSTONE-only columns:")
print(keystone_only)

print("\nACINETOBACTER-only columns:")
print(acinetobacter_only)

# =============================================================================
# COMBINE HARMONIZED DATASETS
# =============================================================================

combined = pd.concat(
    [
        atlas,
        keystone,
        acinetobacter
    ],
    axis=0,
    ignore_index=True,
    sort=False
)


# Confirm successful combination
print("Datasets combined successfully.")

print(f"\nCombined rows: {combined.shape[0]:,}")
print(f"Combined columns: {combined.shape[1]:,}")

# =============================================================================
# VERIFY ROW COUNTS
# =============================================================================

expected_rows = (
    len(atlas)
    + len(keystone)
    + len(acinetobacter)
)

actual_rows = len(combined)


print(f"Expected rows: {expected_rows:,}")
print(f"Actual rows:   {actual_rows:,}")


if actual_rows != expected_rows:
    raise ValueError(
        "Row count mismatch after concatenation."
    )


print("\nRow count check passed.")

# =============================================================================
# VERIFY SOURCE DATABASE CONTRIBUTIONS
# =============================================================================

# Count rows from each source database in the combined dataset
source_counts = (
    combined["Source Database"]
    .value_counts(dropna=False)
)


print("SOURCE DATABASE COUNTS")
print(source_counts)


# Compare with original dataset row counts
print("\nEXPECTED ROW COUNTS")

print(f"Atlas:          {len(atlas):,}")
print(f"Keystone:       {len(keystone):,}")
print(f"Acinetobacter:  {len(acinetobacter):,}")

# =============================================================================
# ORGANIZE COMBINED COLUMN ORDER
# =============================================================================

# Define core harmonized columns to place first
core_columns = [
    "Source Database",
    "Isolate Id",
    "Year",
    "Country",
    "Species",
    "Gender",
    "Age Group",
    "Speciality",
    "Source"
]


# Keep only core columns that exist in the combined dataset
core_columns = [
    column
    for column in core_columns
    if column in combined.columns
]


# Identify all remaining columns
remaining_columns = [
    column
    for column in combined.columns
    if column not in core_columns
]


# Reorder the combined dataset
combined = combined[
    core_columns + remaining_columns
]


# Confirm column order
print("Column order reorganized successfully.")

print("\nFirst columns in combined dataset:")
print(combined.columns[:20].tolist())

print(f"\nTotal columns preserved: {combined.shape[1]:,}")

# =============================================================================
# SAVE INITIAL COMBINED DATASET
# =============================================================================

# -----------------------------------------------------------------------------
# Define the output directory
# -----------------------------------------------------------------------------

output_dir = project_dir / "Combined_v2"
output_dir.mkdir(
    parents=True,
    exist_ok=True,
)


# -----------------------------------------------------------------------------
# Define the output file
# -----------------------------------------------------------------------------

output_csv = output_dir / "AMR_combined_harmonized.csv"


# -----------------------------------------------------------------------------
# Save the combined dataset
# -----------------------------------------------------------------------------

combined.to_csv(
    output_csv,
    index=False,
)


# -----------------------------------------------------------------------------
# Confirm that the output file was created
# -----------------------------------------------------------------------------

if not output_csv.exists():
    raise FileNotFoundError(
        f"CSV export failed: {output_csv}"
    )


# -----------------------------------------------------------------------------
# Report the completed export
# -----------------------------------------------------------------------------

print("Combined harmonized AMR dataset saved successfully.")
print(f"Rows: {combined.shape[0]:,}")
print(f"Columns: {combined.shape[1]:,}")
print(f"CSV: {output_csv}")

print(
    f"File size: "
    f"{output_csv.stat().st_size / (1024**2):,.1f} MB"
)