# -*- coding: utf-8 -*-
"""05_Additional_cleaning_and_harmonization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11u5rX6LWfDpZaZpi6M7QMnbRJ2F0gnO-
"""

# =============================================================================
# LOAD THE COMBINED AMR DATABASE
# =============================================================================

from pathlib import Path

import pandas as pd
from google.colab import drive


# -----------------------------------------------------------------------------
# Mount Google Drive
# -----------------------------------------------------------------------------

drive.mount("/content/drive")


# -----------------------------------------------------------------------------
# Define input path
# -----------------------------------------------------------------------------

input_file = Path(
    "/content/drive/MyDrive/AMR Data Challenge 2026/"
    "Harmonized Database Creation/Combined_v2/"
    "AMR_combined_harmonized.csv"
)


# -----------------------------------------------------------------------------
# Load the combined database
# -----------------------------------------------------------------------------

combined = pd.read_csv(
    input_file,
    low_memory=False
)


# -----------------------------------------------------------------------------
# Confirm successful loading
# -----------------------------------------------------------------------------

print("Database loaded successfully.")
print(f"Rows: {len(combined):,}")
print(f"Columns: {combined.shape[1]:,}")

"""Need to check and harmonize all organism names"""

# =============================================================================
# REVIEW UNIQUE ORGANISM NAMES
# =============================================================================

# Confirm that the required column exists
if "Organism" not in combined.columns:
    raise KeyError("The required column 'Organism' was not found.")


# Count missing organism values
missing_organism_count = combined["Organism"].isna().sum()


# Create a table of exact organism names and their frequencies
organism_summary = (
    combined["Organism"]
    .dropna()
    .value_counts()
    .rename_axis("Organism")
    .reset_index(name="Isolate Count")
    .sort_values(
        by="Organism",
        key=lambda column: column.str.casefold()
    )
    .reset_index(drop=True)
)


# Report basic results
print(f"Unique non-missing organism names: {len(organism_summary):,}")
print(f"Rows with a missing organism name: {missing_organism_count:,}")


# Display every organism name without truncating the table
print("\nComplete organism-name list:")
print(organism_summary.to_string(index=False))

# =============================================================================
# HARMONIZE ORGANISM NAMES
# =============================================================================
#
# Purpose:
# - Preserve the original source-reported Organism column.
# - Create a separate Organism_clean column for harmonized analysis.
# - Correct documented spelling errors and historical names.
# - Apply confirmed taxonomic synonyms and reclassifications.
# - Standardize genus-level, group-level, and ambiguous identifications
#   without inferring unsupported species-level information.
# - Produce a reproducible crosswalk and complete audit of all changes.
#
# Taxonomic reference standard:
# - List of Prokaryotic names with Standing in Nomenclature (LPSN)
# - List of Recommended Names for bacteria of medical importance (LoRN)
# - Accessed: July 15, 2026
#
# Important:
# - The original Organism column is not overwritten.
# - Ambiguous species identifications and organism groups are retained.
# - No fuzzy matching or automated species inference is performed.
# =============================================================================

import re

import pandas as pd
from IPython.display import display


# -----------------------------------------------------------------------------
# Record the nomenclature standard used
# -----------------------------------------------------------------------------

TAXONOMY_REFERENCE_STANDARD = (
    "List of Prokaryotic names with Standing in Nomenclature (LPSN) "
    "and List of Recommended Names for bacteria of medical importance (LoRN)"
)

TAXONOMY_REFERENCE_ACCESS_DATE = "2026-07-15"


# -----------------------------------------------------------------------------
# Confirm that the required column exists
# -----------------------------------------------------------------------------

if "Organism" not in combined.columns:
    raise KeyError(
        "The required column 'Organism' was not found in the combined database."
    )


# Preserve basic information for validation
rows_before_harmonization = len(combined)

missing_before_harmonization = (
    combined["Organism"]
    .isna()
    .sum()
)

unique_before_harmonization = (
    combined["Organism"]
    .nunique(dropna=True)
)


# -----------------------------------------------------------------------------
# Define explicit organism-name harmonization rules
# -----------------------------------------------------------------------------
#
# Each record contains:
# 1. Name currently appearing in the database
# 2. Harmonized name
# 3. Reason for the change
#
# Ambiguous species identifications, species groups, species complexes,
# phenotypic groups, and genus-only identifications are deliberately retained
# at their original level of identification rather than being assigned to a
# single species.
# -----------------------------------------------------------------------------

organism_mapping_records = [

    # =========================================================================
    # Acinetobacter
    # =========================================================================

    (
        "Acinetobacter dijkshoorniae",
        "Acinetobacter lactucae",
        (
            "Confirmed taxonomic synonym; medically recommended "
            "name used"
        ),
    ),
    (
        "Acinetobacter pitii",
        "Acinetobacter pittii",
        "Spelling correction",
    ),

    # =========================================================================
    # Bacteroides and related anaerobes
    # =========================================================================

    (
        "Bacteroides bivius",
        "Prevotella bivia",
        "Confirmed taxonomic reclassification",
    ),
    (
        "Bacteroides capsillosis",
        "Pseudoflavonifractor capillosus",
        (
            "Apparent source spelling correction and confirmed "
            "taxonomic reclassification"
        ),
    ),
    (
        "Bacteroides merdeae",
        "Parabacteroides merdae",
        "Spelling correction and confirmed taxonomic reclassification",
    ),
    (
        "Bacteroides salersyae",
        "Bacteroides salyersiae",
        "Spelling correction",
    ),
    (
        "Bacteroides stercosis",
        "Bacteroides stercoris",
        "Spelling correction",
    ),
    (
        "Bacteroides vulgatus",
        "Phocaeicola vulgatus",
        "Confirmed taxonomic reclassification",
    ),

    # =========================================================================
    # Citrobacter
    # =========================================================================

    (
        "Citrobacter diversus",
        "Citrobacter koseri",
        "Historical taxonomic synonym",
    ),

    # =========================================================================
    # Clostridium and reclassified genera
    # =========================================================================

    (
        "Clostridium aldenense",
        "Enterocloster aldenensis",
        (
            "Confirmed taxonomic reclassification and corrected "
            "epithet agreement"
        ),
    ),
    (
        "Clostridium bifermentans",
        "Paraclostridium bifermentans",
        "Confirmed taxonomic reclassification",
    ),
    (
        "Clostridium bolteae",
        "Enterocloster bolteae",
        "Confirmed taxonomic reclassification",
    ),
    (
        "Clostridium citroniae",
        "Enterocloster citroniae",
        "Confirmed taxonomic reclassification",
    ),
    (
        "Clostridium clostridiiformis",
        "Enterocloster clostridioformis",
        "Taxonomic reclassification and corrected epithet",
    ),
    (
        "Clostridium hathewayi",
        "Hungatella hathewayi",
        "Confirmed taxonomic reclassification",
    ),
    (
        "Clostridium novyia",
        "Clostridium novyi",
        "Spelling correction",
    ),
    (
        "Clostridium scatalogenes",
        "Clostridium scatologenes",
        "Spelling correction",
    ),

    # UPDATED:
    # Paeniclostridium sordellii is the current LPSN/LoRN recommended name.
    (
        "Clostridium sordellii",
        "Paeniclostridium sordellii",
        (
            "Confirmed taxonomic reclassification; medically recommended "
            "name used"
        ),
    ),
    (
        "Paeniclostridium sordelli",
        "Paeniclostridium sordellii",
        "Spelling correction",
    ),

    # =========================================================================
    # Enterobacter and related genera
    # =========================================================================

    (
        "Enterobacter agglomerans",
        "Pantoea agglomerans",
        "Confirmed taxonomic reclassification",
    ),
    (
        "Enterobacter gergoviae",
        "Pluralibacter gergoviae",
        "Confirmed taxonomic reclassification",
    ),
    (
        "Enterobacter hormaechi",
        "Enterobacter hormaechei",
        "Spelling correction",
    ),
    (
        "Enterobacter sakazakii",
        "Cronobacter sakazakii",
        "Confirmed taxonomic reclassification",
    ),
    (
        "Enterobacter taylorae",
        "Enterobacter cancerogenus",
        "Confirmed taxonomic synonym",
    ),

    # =========================================================================
    # Other confirmed spelling corrections, synonyms, or reclassifications
    # =========================================================================

    (
        "Escherichia hermanii",
        "Escherichia hermannii",
        "Spelling correction",
    ),
    (
        "Eubacterium lentum",
        "Eggerthella lenta",
        "Confirmed taxonomic reclassification",
    ),
    (
        "Proteus rettgeri",
        "Providencia rettgeri",
        "Confirmed taxonomic reclassification",
    ),
    (
        "Raoultella ornithinolytica",
        "Klebsiella ornithinolytica",
        (
            "Confirmed taxonomic synonym; medically recommended "
            "name used"
        ),
    ),
    (
        "Raoultella planticola",
        "Klebsiella planticola",
        (
            "Confirmed taxonomic synonym; medically recommended "
            "name used"
        ),
    ),

    # =========================================================================
    # Historical Peptostreptococcus names
    # =========================================================================

    (
        "Peptostreptococcus hydrogenalis",
        "Anaerococcus hydrogenalis",
        "Confirmed taxonomic reclassification",
    ),
    (
        "Peptostreptococcus indolicus",
        "Peptoniphilus indolicus",
        "Confirmed taxonomic reclassification",
    ),
    (
        "Peptostreptococcus lactolyticus",
        "Anaerococcus lactolyticus",
        "Confirmed taxonomic reclassification",
    ),
    (
        "Peptostreptococcus magnus",
        "Finegoldia magna",
        "Confirmed taxonomic reclassification",
    ),
    (
        "Peptostreptococcus tetradius",
        "Anaerococcus tetradius",
        "Confirmed taxonomic reclassification",
    ),

    # =========================================================================
    # Prevotella, Staphylococcus, and Streptococcus corrections
    # =========================================================================

    (
        "Prevotella nanceinsis",
        "Prevotella nanceiensis",
        "Spelling correction",
    ),
    (
        "Staphylococcus pseudointermedius",
        "Staphylococcus pseudintermedius",
        "Spelling correction",
    ),
    (
        "Streptococcus sanguis",
        "Streptococcus sanguinis",
        "Historical name and corrected nomenclatural spelling",
    ),

    # =========================================================================
    # Non-speciated genus-level labels
    # =========================================================================
    #
    # These changes standardize the terminology used for isolates identified
    # only to the genus level. No species-level identification is inferred.
    # =========================================================================

    (
        "Acinetobacter, non-speciated",
        "Acinetobacter spp.",
        "Non-speciated genus-level label standardization",
    ),
    (
        "Unspeciated Acinetobacter",
        "Acinetobacter spp.",
        "Non-speciated genus-level label standardization",
    ),
    (
        "Citrobacter, non-speciated",
        "Citrobacter spp.",
        "Non-speciated genus-level label standardization",
    ),
    (
        "Unspeciated Citrobacter",
        "Citrobacter spp.",
        "Non-speciated genus-level label standardization",
    ),
    (
        "Enterobacter, non-speciated",
        "Enterobacter spp.",
        "Non-speciated genus-level label standardization",
    ),
    (
        "Unspeciated Enterobacter",
        "Enterobacter spp.",
        "Non-speciated genus-level label standardization",
    ),
    (
        "Enterococcus, non-speciated",
        "Enterococcus spp.",
        "Non-speciated genus-level label standardization",
    ),
    (
        "Klebsiella, non-speciated",
        "Klebsiella spp.",
        "Non-speciated genus-level label standardization",
    ),
    (
        "Providencia, non-speciated",
        "Providencia spp.",
        "Non-speciated genus-level label standardization",
    ),
    (
        "Unspeciated Providencia",
        "Providencia spp.",
        "Non-speciated genus-level label standardization",
    ),
    (
        "Serratia, non-speciated",
        "Serratia spp.",
        "Non-speciated genus-level label standardization",
    ),
    (
        "Unspeciated Serratia",
        "Serratia spp.",
        "Non-speciated genus-level label standardization",
    ),
    (
        "Unspeciated Cedecea",
        "Cedecea spp.",
        "Non-speciated genus-level label standardization",
    ),
    (
        "Unspeciated Cronobacter",
        "Cronobacter spp.",
        "Non-speciated genus-level label standardization",
    ),
    (
        "Unspeciated Erwinia",
        "Erwinia spp.",
        "Non-speciated genus-level label standardization",
    ),
    (
        "Unspeciated Pantoea",
        "Pantoea spp.",
        "Non-speciated genus-level label standardization",
    ),
    (
        "Unspeciated Raoultella",
        "Raoultella spp.",
        (
            "Non-speciated genus-level label retained and standardized; "
            "no species-level reassignment inferred"
        ),
    ),
    (
        "Unspeciated Salmonella",
        "Salmonella spp.",
        "Non-speciated genus-level label standardization",
    ),
    (
        "Unspeciated Staphylococcus",
        "Staphylococcus spp.",
        "Non-speciated genus-level label standardization",
    ),

    # =========================================================================
    # Coagulase-negative Staphylococcus group
    # =========================================================================
    #
    # This is a phenotypic organism group rather than an individual species.
    # =========================================================================

    (
        "Staphylococcus Coagulase Negative",
        "Coagulase-negative Staphylococcus spp.",
        "Phenotypic group-label standardization",
    ),
    (
        "Unspeciated coagulase-negative staphylococci",
        "Coagulase-negative Staphylococcus spp.",
        "Phenotypic group-label standardization",
    ),

    # =========================================================================
    # Formatting variants of explicitly ambiguous identifications
    # =========================================================================
    #
    # These labels are standardized only for formatting. Their ambiguity is
    # retained, and no isolate is assigned to one member of the group.
    # =========================================================================

    (
        "Citrobacter amalonaticus / farmeri",
        "Citrobacter amalonaticus/farmeri",
        "Formatting standardized; ambiguous identification retained",
    ),
    (
        "Pseudomonas putida/fluorescens Group",
        "Pseudomonas putida/fluorescens group",
        "Formatting standardized; group identification retained",
    ),
    (
        "Staphylococcus cohnii / Staphylococcus ureilyticus",
        "Staphylococcus cohnii/Staphylococcus ureilyticus",
        "Formatting standardized; ambiguous identification retained",
    ),
    (
        "Staphylococcus pseudintermedius / intermedius / delphini",
        "Staphylococcus pseudintermedius/intermedius/delphini",
        "Formatting standardized; ambiguous identification retained",
    ),
    (
        "Streptococcus mitis/ oralis",
        "Streptococcus mitis/oralis",
        "Formatting standardized; ambiguous identification retained",
    ),
    (
        "Streptococcus mitis_oralis",
        "Streptococcus mitis/oralis",
        "Formatting standardized; ambiguous identification retained",
    ),
    (
        "Streptococcus salivarius/ vestibularis",
        "Streptococcus salivarius/vestibularis",
        "Formatting standardized; ambiguous identification retained",
    ),
]


# -----------------------------------------------------------------------------
# Convert the harmonization rules into an auditable crosswalk
# -----------------------------------------------------------------------------

organism_mapping_table = pd.DataFrame(
    organism_mapping_records,
    columns=[
        "Original Name",
        "Organism_clean",
        "Reason",
    ],
)

# Add reference-standard metadata to the crosswalk
organism_mapping_table["Reference Standard"] = (
    TAXONOMY_REFERENCE_STANDARD
)

organism_mapping_table["Reference Access Date"] = (
    TAXONOMY_REFERENCE_ACCESS_DATE
)


# Confirm that every original mapping label appears only once
duplicated_mapping_names = organism_mapping_table.loc[
    organism_mapping_table["Original Name"].duplicated(keep=False),
    "Original Name",
]

if not duplicated_mapping_names.empty:
    raise ValueError(
        "Duplicate original names were found in the organism mapping:\n"
        + "\n".join(
            sorted(
                duplicated_mapping_names
                .astype(str)
                .unique()
                .tolist()
            )
        )
    )


# Create dictionaries used to apply and audit the mappings
organism_mapping = dict(
    zip(
        organism_mapping_table["Original Name"],
        organism_mapping_table["Organism_clean"],
    )
)

organism_reason_mapping = dict(
    zip(
        organism_mapping_table["Original Name"],
        organism_mapping_table["Reason"],
    )
)


# -----------------------------------------------------------------------------
# Apply basic non-taxonomic text normalization
# -----------------------------------------------------------------------------

# Convert to pandas string type while preserving missing values.
# This does not overwrite the original column in the combined database.
organism_original = combined["Organism"].astype("string")

organism_normalized = (
    organism_original
    .str.strip()
    .str.replace(
        r"\s+",
        " ",
        regex=True,
    )
    # Standardize terminal sp, sp., spp, or spp. as spp.
    # Matching is case-insensitive so SP., SPP., etc. are also standardized.
    .str.replace(
        r"\s+spp?\.?$",
        " spp.",
        regex=True,
        flags=re.IGNORECASE,
    )
)


# -----------------------------------------------------------------------------
# Apply explicit spelling and taxonomic harmonization rules
# -----------------------------------------------------------------------------

organism_clean = organism_normalized.replace(
    organism_mapping
)


# -----------------------------------------------------------------------------
# Classify the identification resolution
# -----------------------------------------------------------------------------
#
# This variable helps prevent genus-only records, species groups, and ambiguous
# identifications from being treated as confirmed individual species in later
# analyses.
#
# "Named taxon" does not automatically guarantee that the record is eligible
# for a species-specific analysis. It means that the label was not recognized
# as one of the explicitly lower-resolution categories below.
# -----------------------------------------------------------------------------

def classify_organism_identification(organism_name):
    if pd.isna(organism_name):
        return "Missing"

    name = str(organism_name).strip()
    name_casefold = name.casefold()

    if name_casefold == "coagulase-negative staphylococcus spp.":
        return "Phenotypic organism group"

    if "/" in name:
        return "Ambiguous multi-taxon identification"

    if (
        name_casefold.endswith(" group")
        or name_casefold.endswith(" complex")
        or " species group" in name_casefold
        or " species complex" in name_casefold
    ):
        return "Species group or complex"

    if re.search(
        r"\bspp\.$",
        name_casefold,
    ):
        return "Genus-level identification"

    return "Named taxon"


organism_identification_type = (
    organism_clean
    .map(classify_organism_identification)
    .astype("string")
)


# -----------------------------------------------------------------------------
# Add harmonized variables to the combined database
# -----------------------------------------------------------------------------

# Drop existing derived versions first so the cell can be safely rerun.
derived_organism_columns = [
    "Organism_clean",
    "Organism_identification_type",
]

columns_to_drop = [
    column
    for column in derived_organism_columns
    if column in combined.columns
]

if columns_to_drop:
    combined = combined.drop(
        columns=columns_to_drop
    )


# Place the derived fields directly after the original Organism column.
organism_column_position = (
    combined.columns.get_loc("Organism") + 1
)

combined.insert(
    organism_column_position,
    "Organism_clean",
    organism_clean,
)

combined.insert(
    organism_column_position + 1,
    "Organism_identification_type",
    organism_identification_type,
)


# =============================================================================
# VALIDATE AND AUDIT THE HARMONIZATION
# =============================================================================

# -----------------------------------------------------------------------------
# Confirm that no database records were added or removed
# -----------------------------------------------------------------------------

assert len(combined) == rows_before_harmonization, (
    "The row count changed during organism harmonization."
)


# -----------------------------------------------------------------------------
# Confirm that organism missingness did not change
# -----------------------------------------------------------------------------

assert (
    combined["Organism_clean"].isna().sum()
    == missing_before_harmonization
), (
    "The number of missing organism values changed during harmonization."
)


# Confirm that the identification-type variable is populated for every row.
assert combined["Organism_identification_type"].notna().all(), (
    "Missing Organism_identification_type values were generated."
)


# -----------------------------------------------------------------------------
# Calculate overall harmonization results
# -----------------------------------------------------------------------------

unique_after_harmonization = (
    combined["Organism_clean"]
    .nunique(dropna=True)
)

changed_row_mask = (
    organism_original.fillna("<MISSING>")
    != combined["Organism_clean"].fillna("<MISSING>")
)

changed_row_count = int(
    changed_row_mask.sum()
)


# Identify records changed through an explicit mapping
explicit_mapping_row_mask = (
    organism_normalized.isin(organism_mapping)
)

explicit_mapping_row_count = int(
    explicit_mapping_row_mask.sum()
)


# Identify records changed only through general text normalization
normalization_only_row_mask = (
    changed_row_mask
    & ~explicit_mapping_row_mask
)

normalization_only_row_count = int(
    normalization_only_row_mask.sum()
)


# -----------------------------------------------------------------------------
# Identify explicit mapping entries not found in the current database
# -----------------------------------------------------------------------------

names_present = set(
    organism_normalized
    .dropna()
    .unique()
)

unused_mapping_names = sorted(
    set(organism_mapping) - names_present,
    key=str.casefold,
)

unused_mapping_table = (
    organism_mapping_table.loc[
        organism_mapping_table["Original Name"].isin(
            unused_mapping_names
        )
    ]
    .copy()
    .reset_index(drop=True)
)


# -----------------------------------------------------------------------------
# Create a complete audit showing every original/clean label combination
# -----------------------------------------------------------------------------

organism_audit = (
    pd.DataFrame(
        {
            "Organism": organism_original,
            "Organism_normalized": organism_normalized,
            "Organism_clean": combined["Organism_clean"],
            "Organism_identification_type": (
                combined["Organism_identification_type"]
            ),
        }
    )
    .value_counts(dropna=False)
    .rename("Row Count")
    .reset_index()
)


# Attach the documented reason using the normalized source label.
organism_audit["Reason"] = (
    organism_audit["Organism_normalized"]
    .map(organism_reason_mapping)
)


# Determine which labels changed between the source and cleaned fields.
audit_changed_mask = (
    organism_audit["Organism"].fillna("<MISSING>")
    != organism_audit["Organism_clean"].fillna("<MISSING>")
)


# Assign a reason to labels changed only through general text normalization.
formatting_only_mask = (
    audit_changed_mask
    & organism_audit["Reason"].isna()
)

organism_audit.loc[
    formatting_only_mask,
    "Reason",
] = (
    "Whitespace, capitalization of sp./spp., or terminal "
    "sp./spp. notation standardized"
)


# Retain only changed labels for the main change audit.
organism_changes = (
    organism_audit.loc[
        audit_changed_mask,
        [
            "Organism",
            "Organism_clean",
            "Organism_identification_type",
            "Reason",
            "Row Count",
        ],
    ]
    .sort_values(
        by=[
            "Organism_clean",
            "Organism",
        ],
        key=lambda column: (
            column.astype("string").str.casefold()
        ),
        na_position="last",
    )
    .reset_index(drop=True)
)


# -----------------------------------------------------------------------------
# Create a summary of identification resolution
# -----------------------------------------------------------------------------

organism_identification_summary = (
    combined["Organism_identification_type"]
    .value_counts(dropna=False)
    .rename_axis("Organism identification type")
    .reset_index(name="Row Count")
)

organism_identification_summary["Percent of database"] = (
    organism_identification_summary["Row Count"]
    .div(len(combined))
    .mul(100)
    .round(2)
)


# -----------------------------------------------------------------------------
# Validate audit totals
# -----------------------------------------------------------------------------

assert organism_audit["Row Count"].sum() == len(combined), (
    "The organism audit row counts do not sum to the database row count."
)

assert organism_changes["Row Count"].sum() == changed_row_count, (
    "The changed-label audit does not match the number of changed rows."
)

assert (
    explicit_mapping_row_count
    + normalization_only_row_count
    == changed_row_count
), (
    "Explicitly mapped and normalization-only row counts do not sum "
    "to the total number of changed rows."
)


# =============================================================================
# REPORT THE RESULTS
# =============================================================================

print("Organism harmonization completed successfully.")

print("\nTaxonomic reference standard:")
print(f"  {TAXONOMY_REFERENCE_STANDARD}")
print(
    "Taxonomic reference access date: "
    f"{TAXONOMY_REFERENCE_ACCESS_DATE}"
)

print("\nDatabase validation:")
print(f"  Rows in database: {len(combined):,}")
print(
    "  Missing original Organism values: "
    f"{missing_before_harmonization:,}"
)
print(
    "  Missing Organism_clean values: "
    f"{combined['Organism_clean'].isna().sum():,}"
)

print("\nHarmonization results:")
print(
    "  Explicit crosswalk rules defined: "
    f"{len(organism_mapping_table):,}"
)
print(
    "  Distinct harmonized crosswalk outputs: "
    f"{organism_mapping_table['Organism_clean'].nunique():,}"
)
print(
    "  Unique organism labels before harmonization: "
    f"{unique_before_harmonization:,}"
)
print(
    "  Unique organism labels after harmonization: "
    f"{unique_after_harmonization:,}"
)
print(
    "  Rows with any changed organism label: "
    f"{changed_row_count:,}"
)
print(
    "  Rows changed through an explicit crosswalk rule: "
    f"{explicit_mapping_row_count:,}"
)
print(
    "  Rows changed only through general text normalization: "
    f"{normalization_only_row_count:,}"
)


# -----------------------------------------------------------------------------
# Report unused crosswalk entries
# -----------------------------------------------------------------------------

if unused_mapping_names:
    print(
        "\nExplicit mapping entries not found in the current database:"
    )

    for organism_name in unused_mapping_names:
        print(f"  - {organism_name}")

else:
    print(
        "\nAll explicit mapping entries were found in the current database."
    )


# -----------------------------------------------------------------------------
# Display reproducibility and audit tables
# -----------------------------------------------------------------------------

print("\nComplete organism harmonization crosswalk:")
display(
    organism_mapping_table
)

print("\nComplete audit of changed organism labels:")
display(
    organism_changes
)

print("\nSummary of organism identification resolution:")
display(
    organism_identification_summary
)

if not unused_mapping_table.empty:
    print("\nCrosswalk entries not used in the current database:")
    display(
        unused_mapping_table
    )


# =============================================================================
# OPTIONAL: SAVE THE CROSSWALK AND AUDIT TABLES
# =============================================================================
#
# Uncomment and update the path if you want to save these tables as permanent
# reproducibility outputs.
#
from pathlib import Path
#
organism_audit_output_directory = Path(
     "/content/drive/MyDrive/AMR Data Challenge 2026/"
     "Harmonized Database Creation/Audit Outputs"
)
#
organism_audit_output_directory.mkdir(
     parents=True,
     exist_ok=True,
)
#
organism_mapping_table.to_csv(
     organism_audit_output_directory
     / "organism_harmonization_crosswalk.csv",
     index=False,
)
#
organism_changes.to_csv(
     organism_audit_output_directory
     / "organism_harmonization_changes_with_row_counts.csv",
     index=False,
)
#
# organism_identification_summary.to_csv(
#     organism_audit_output_directory
#     / "organism_identification_resolution_summary.csv",
#     index=False,
# )
#
unused_mapping_table.to_csv(
     organism_audit_output_directory
     / "unused_organism_mapping_entries.csv",
     index=False,
)
#
print(
     "\nOrganism harmonization audit outputs saved to:"
)
print(organism_audit_output_directory)

"""Check antibiotic names"""

# =============================================================================
# AUDIT ANTIBIOTIC COLUMN NAMES AND MIC–INTERPRETATION PAIRS
# =============================================================================

import re

import pandas as pd
from IPython.display import display


# -----------------------------------------------------------------------------
# Define the expected harmonized antibiotic names
# -----------------------------------------------------------------------------
#
# This is the authoritative antibiotic registry for the three merged databases.
# It allows the audit to detect:
# - MIC columns without interpretation columns;
# - interpretation columns without MIC columns;
# - entirely missing expected antibiotic pairs;
# - unexpected additional interpretation columns.
# -----------------------------------------------------------------------------

expected_antibiotics = [
    "Amikacin",
    "Amoxycillin clavulanate",
    "Ampicillin",
    "Ampicillin sulbactam",
    "Azithromycin",
    "Aztreonam",
    "Aztreonam avibactam",
    "Cefepime",
    "Cefiderocol",
    "Cefixime",
    "Cefoperazone sulbactam",
    "Cefoxitin",
    "Cefpodoxime",
    "Ceftaroline",
    "Ceftazidime",
    "Ceftazidime avibactam",
    "Ceftibuten",
    "Ceftolozane tazobactam",
    "Ceftriaxone",
    "Ciprofloxacin",
    "Clarithromycin",
    "Clindamycin",
    "Colistin",
    "Daptomycin",
    "Doripenem",
    "Doxycycline",
    "Ertapenem",
    "Erythromycin",
    "Gatifloxacin",
    "Gentamicin",
    "Imipenem",
    "Levofloxacin",
    "Linezolid",
    "Meropenem",
    "Meropenem vaborbactam",
    "Metronidazole",
    "Minocycline",
    "Moxifloxacin",
    "Omadacycline",
    "Oxacillin",
    "Penicillin",
    "Piperacillin tazobactam",
    "Quinupristin dalfopristin",
    "Sulbactam",
    "Sulbactam/514 at 4 mcg/ml",
    "Teicoplanin",
    "Tetracycline",
    "Tigecycline",
    "Trimethoprim sulfa",
    "Vancomycin",
]


# Confirm that the registry itself does not contain duplicates
if len(expected_antibiotics) != len(set(expected_antibiotics)):
    raise ValueError(
        "Duplicate names were found in expected_antibiotics."
    )


# -----------------------------------------------------------------------------
# Create a complete indexed list of database columns
# -----------------------------------------------------------------------------

all_column_names = pd.DataFrame(
    {
        "Column Position": range(1, len(combined.columns) + 1),
        "Column Name": combined.columns.astype(str),
    }
)


# -----------------------------------------------------------------------------
# Check for malformed or duplicate column names
# -----------------------------------------------------------------------------

def normalize_column_name(column_name):
    """Normalize a column name for comparison without changing the database."""

    return re.sub(
        r"\s+",
        " ",
        str(column_name).strip(),
    ).casefold()


all_column_names["Normalized Column Name"] = (
    all_column_names["Column Name"]
    .map(normalize_column_name)
)


# Exact duplicate names
duplicate_column_names = all_column_names.loc[
    all_column_names["Column Name"].duplicated(keep=False)
].copy()


# Names that become duplicates after case and whitespace normalization
normalized_duplicate_column_names = all_column_names.loc[
    all_column_names["Normalized Column Name"].duplicated(
        keep=False
    )
].copy()


# Leading/trailing spaces, repeated spaces, tabs, or line breaks
column_format_issue_mask = (
    all_column_names["Column Name"]
    .ne(all_column_names["Column Name"].str.strip())
    |
    all_column_names["Column Name"]
    .str.contains(r"\s{2,}|\n|\r|\t", regex=True, na=False)
)

column_name_format_issues = all_column_names.loc[
    column_format_issue_mask
].copy()


# -----------------------------------------------------------------------------
# Check for previously identified unharmonized source names
# -----------------------------------------------------------------------------

known_unharmonized_antibiotic_aliases = {
    "Amoxicillin-clavulanic acid": "Amoxycillin clavulanate",
    "Piperacillin-tazobactam": "Piperacillin tazobactam",
    "Trimethoprim-sulfamethoxazole": "Trimethoprim sulfa",
}

unharmonized_alias_records = []

for original_name, harmonized_name in (
    known_unharmonized_antibiotic_aliases.items()
):
    for suffix in ["", "_I"]:
        original_column = original_name + suffix

        if original_column in combined.columns:
            unharmonized_alias_records.append(
                {
                    "Unharmonized Column": original_column,
                    "Expected Harmonized Column": (
                        harmonized_name + suffix
                    ),
                }
            )

unharmonized_aliases_present = pd.DataFrame(
    unharmonized_alias_records,
    columns=[
        "Unharmonized Column",
        "Expected Harmonized Column",
    ],
)


# -----------------------------------------------------------------------------
# Identify all observed interpretation columns
# -----------------------------------------------------------------------------

observed_interpretation_columns = [
    str(column)
    for column in combined.columns
    if str(column).endswith("_I")
]

observed_interpretation_antibiotics = [
    column[:-2]
    for column in observed_interpretation_columns
]


# Include unexpected interpretation columns in the audit
unexpected_interpretation_antibiotics = sorted(
    set(observed_interpretation_antibiotics)
    - set(expected_antibiotics),
    key=str.casefold,
)

antibiotics_to_audit = (
    expected_antibiotics
    + unexpected_interpretation_antibiotics
)


# -----------------------------------------------------------------------------
# Check both sides of every expected MIC–interpretation pair
# -----------------------------------------------------------------------------

antibiotic_pair_records = []

for antibiotic_name in antibiotics_to_audit:
    mic_column = antibiotic_name
    interpretation_column = f"{antibiotic_name}_I"

    mic_column_present = mic_column in combined.columns
    interpretation_column_present = (
        interpretation_column in combined.columns
    )

    if mic_column_present and interpretation_column_present:
        pair_status = "Complete pair"
    elif mic_column_present:
        pair_status = "Interpretation column missing"
    elif interpretation_column_present:
        pair_status = "MIC column missing"
    else:
        pair_status = "Both columns missing"

    antibiotic_pair_records.append(
        {
            "Antibiotic Name": antibiotic_name,
            "Expected Antibiotic": (
                antibiotic_name in expected_antibiotics
            ),
            "MIC Column": mic_column,
            "Interpretation Column": interpretation_column,
            "MIC Column Present": mic_column_present,
            "Interpretation Column Present": (
                interpretation_column_present
            ),
            "Pair Status": pair_status,
        }
    )


antibiotic_pair_summary = (
    pd.DataFrame(antibiotic_pair_records)
    .sort_values(
        by="Antibiotic Name",
        key=lambda column: column.str.casefold(),
    )
    .reset_index(drop=True)
)


incomplete_expected_pairs = antibiotic_pair_summary.loc[
    antibiotic_pair_summary["Expected Antibiotic"]
    & antibiotic_pair_summary["Pair Status"].ne("Complete pair")
].copy()


unexpected_antibiotic_pairs = antibiotic_pair_summary.loc[
    ~antibiotic_pair_summary["Expected Antibiotic"]
].copy()


# -----------------------------------------------------------------------------
# Audit row-level completeness and interpretation values
# -----------------------------------------------------------------------------

valid_interpretation_values = {
    "Susceptible",
    "Resistant",
}

antibiotic_value_records = []
unexpected_interpretation_records = []

for antibiotic_name in antibiotics_to_audit:
    mic_column = antibiotic_name
    interpretation_column = f"{antibiotic_name}_I"

    if not (
        mic_column in combined.columns
        and interpretation_column in combined.columns
    ):
        continue

    mic_present = combined[mic_column].notna()
    interpretation_present = (
        combined[interpretation_column].notna()
    )

    observed_values = set(
        combined[interpretation_column]
        .dropna()
        .astype("string")
        .str.strip()
        .unique()
    )

    unexpected_values = sorted(
        observed_values - valid_interpretation_values,
        key=str.casefold,
    )

    antibiotic_value_records.append(
        {
            "Antibiotic Name": antibiotic_name,
            "MIC Values Present": int(mic_present.sum()),
            "Interpretations Present": int(
                interpretation_present.sum()
            ),
            "Both Present": int(
                (mic_present & interpretation_present).sum()
            ),
            "MIC Present but Interpretation Missing": int(
                (mic_present & ~interpretation_present).sum()
            ),
            "Interpretation Present but MIC Missing": int(
                (~mic_present & interpretation_present).sum()
            ),
            "Unexpected Interpretation Values": (
                ", ".join(unexpected_values)
                if unexpected_values
                else ""
            ),
        }
    )

    for unexpected_value in unexpected_values:
        unexpected_interpretation_records.append(
            {
                "Antibiotic Name": antibiotic_name,
                "Unexpected Value": unexpected_value,
                "Row Count": int(
                    combined[interpretation_column]
                    .astype("string")
                    .str.strip()
                    .eq(unexpected_value)
                    .sum()
                ),
            }
        )


antibiotic_value_summary = pd.DataFrame(
    antibiotic_value_records
)

unexpected_interpretation_values = pd.DataFrame(
    unexpected_interpretation_records,
    columns=[
        "Antibiotic Name",
        "Unexpected Value",
        "Row Count",
    ],
)


# Interpretation without an MIC is a potentially serious inconsistency.
interpretation_without_mic = antibiotic_value_summary.loc[
    antibiotic_value_summary[
        "Interpretation Present but MIC Missing"
    ].gt(0)
].copy()


# -----------------------------------------------------------------------------
# Report results
# -----------------------------------------------------------------------------

complete_expected_pair_count = int(
    (
        antibiotic_pair_summary["Expected Antibiotic"]
        & antibiotic_pair_summary["Pair Status"].eq(
            "Complete pair"
        )
    ).sum()
)

print("=" * 80)
print("ANTIBIOTIC COLUMN AUDIT")
print("=" * 80)

print(f"Total database columns: {len(combined.columns):,}")
print(f"Expected antibiotics: {len(expected_antibiotics):,}")
print(
    "Observed interpretation columns ending in '_I': "
    f"{len(observed_interpretation_columns):,}"
)
print(
    "Complete expected MIC–interpretation pairs: "
    f"{complete_expected_pair_count:,}"
)
print(
    "Incomplete expected pairs: "
    f"{len(incomplete_expected_pairs):,}"
)
print(
    "Unexpected antibiotic interpretation columns: "
    f"{len(unexpected_antibiotic_pairs):,}"
)


print("\nComplete antibiotic-pair audit:")
display(antibiotic_pair_summary)


print("\nRow-level MIC and interpretation audit:")
display(antibiotic_value_summary)


print("\nExact duplicate column names:")
if duplicate_column_names.empty:
    print("None identified.")
else:
    display(duplicate_column_names)


print("\nCase- or whitespace-normalized duplicate column names:")
if normalized_duplicate_column_names.empty:
    print("None identified.")
else:
    display(normalized_duplicate_column_names)


print("\nMalformed or whitespace-affected column names:")
if column_name_format_issues.empty:
    print("None identified.")
else:
    display(column_name_format_issues)


print("\nPreviously identified unharmonized antibiotic aliases:")
if unharmonized_aliases_present.empty:
    print("None identified.")
else:
    display(unharmonized_aliases_present)


print("\nIncomplete expected antibiotic pairs:")
if incomplete_expected_pairs.empty:
    print("None identified.")
else:
    display(incomplete_expected_pairs)


print("\nUnexpected antibiotic pairs:")
if unexpected_antibiotic_pairs.empty:
    print("None identified.")
else:
    display(unexpected_antibiotic_pairs)


print("\nUnexpected interpretation values:")
if unexpected_interpretation_values.empty:
    print("None identified.")
else:
    display(unexpected_interpretation_values)


print("\nInterpretations present without corresponding MIC values:")
if interpretation_without_mic.empty:
    print("None identified.")
else:
    display(interpretation_without_mic)

# =============================================================================
# AUDIT MIC SCIENTIFIC NOTATION AND FLOATING-POINT PRECISION ARTIFACTS
# =============================================================================
#
# Purpose:
# - Identify MIC values stored in scientific notation.
# - Distinguish ordinary scientific notation from unusually long
#   floating-point representations.
# - Quantify the frequency by source database and antibiotic.
# - Confirm whether the long representations are numerically equivalent
#   to their shorter decimal forms.
# - Identify any MIC values that cannot be parsed as a number with an
#   optional censoring operator.
#
# Important:
# - This section does not modify the combined database.
# - Original MIC values and censoring operators are retained unchanged.
# - No MIC measurement is rounded, replaced, or reclassified.
# =============================================================================

import re

import pandas as pd
from IPython.display import display


# -----------------------------------------------------------------------------
# Confirm that the required objects are available
# -----------------------------------------------------------------------------

if "expected_antibiotics" not in globals():
    raise NameError(
        "expected_antibiotics was not found. Run the antibiotic-column "
        "audit section before running this section."
    )

if not combined.index.is_unique:
    raise ValueError(
        "The combined DataFrame index is not unique. A unique index is "
        "required to create an unambiguous row-level MIC audit."
    )


# Preserve basic structural information to confirm that this audit does not
# modify the database.
rows_before_mic_precision_audit = len(combined)
columns_before_mic_precision_audit = combined.columns.copy()


# -----------------------------------------------------------------------------
# Identify expected MIC columns that are present
# -----------------------------------------------------------------------------

mic_columns = [
    antibiotic_name
    for antibiotic_name in expected_antibiotics
    if antibiotic_name in combined.columns
]


# -----------------------------------------------------------------------------
# Define valid MIC formatting patterns
# -----------------------------------------------------------------------------
#
# Accepted examples:
# 0.015
# 2
# .5
# <=0.03
# <= 0.03
# >16
# 2E-3
# 1.4999999999999999E-2
# -----------------------------------------------------------------------------

mic_value_pattern = re.compile(
    r"^(?P<operator><=|>=|<|>)?"
    r"\s*"
    r"(?P<number>"
    r"(?:\d+(?:\.\d*)?|\.\d+)"
    r"(?:[eE][+-]?\d+)?"
    r")$"
)


# Scientific notation containing a very long decimal mantissa is flagged
# as a possible floating-point representation artifact.
long_scientific_notation_pattern = re.compile(
    r"^(?:<=|>=|<|>)?"
    r"\s*"
    r"(?:\d+\.\d{10,}|\.\d{10,})"
    r"[eE][+-]?\d+$"
)


# -----------------------------------------------------------------------------
# Inspect every observed MIC value
# -----------------------------------------------------------------------------

scientific_notation_records = []
precision_artifact_records = []
unparseable_mic_records = []

total_observed_mic_values = 0


for mic_column in mic_columns:

    mic_values = (
        combined[mic_column]
        .astype("string")
        .str.strip()
    )

    # Treat empty strings as missing for the audit only.
    mic_values = mic_values.mask(
        mic_values.eq("")
    )

    total_observed_mic_values += int(
        mic_values.notna().sum()
    )

    for row_index, raw_mic_value in mic_values.dropna().items():

        raw_mic_value = str(raw_mic_value)

        mic_match = mic_value_pattern.fullmatch(
            raw_mic_value
        )

        # Record any value that cannot be interpreted as a numeric MIC
        # with an optional censoring operator.
        if mic_match is None:

            unparseable_record = {
                "DataFrame Index": row_index,
                "Antibiotic Name": mic_column,
                "Raw MIC Value": raw_mic_value,
            }

            if "Source Database" in combined.columns:
                unparseable_record["Source Database"] = (
                    combined.at[row_index, "Source Database"]
                )

            if "Isolate Id" in combined.columns:
                unparseable_record["Isolate Id"] = (
                    combined.at[row_index, "Isolate Id"]
                )

            unparseable_mic_records.append(
                unparseable_record
            )

            continue

        operator = mic_match.group("operator") or ""
        numeric_text = mic_match.group("number")

        # Continue only if the numeric component uses scientific notation.
        if not re.search(r"[eE]", numeric_text):
            continue

        numeric_value = float(numeric_text)

        # Create a concise representation for comparison only.
        # This does not replace the original database value.
        concise_numeric_text = format(
            numeric_value,
            ".15g",
        )

        concise_mic_display = (
            f"{operator}{concise_numeric_text}"
        )

        numeric_equivalence_confirmed = (
            float(numeric_text)
            == float(concise_numeric_text)
        )

        is_long_precision_artifact = bool(
            long_scientific_notation_pattern.fullmatch(
                raw_mic_value
            )
        )

        scientific_record = {
            "DataFrame Index": row_index,
            "Antibiotic Name": mic_column,
            "Raw MIC Value": raw_mic_value,
            "Operator": operator,
            "Parsed Numeric MIC": numeric_value,
            "Concise Numeric Representation": (
                concise_mic_display
            ),
            "Long Precision Artifact": (
                is_long_precision_artifact
            ),
            "Numeric Equivalence Confirmed": (
                numeric_equivalence_confirmed
            ),
        }

        if "Source Database" in combined.columns:
            scientific_record["Source Database"] = (
                combined.at[row_index, "Source Database"]
            )

        if "Isolate Id" in combined.columns:
            scientific_record["Isolate Id"] = (
                combined.at[row_index, "Isolate Id"]
            )

        scientific_notation_records.append(
            scientific_record
        )

        if is_long_precision_artifact:
            precision_artifact_records.append(
                scientific_record.copy()
            )


# -----------------------------------------------------------------------------
# Convert the audit records into tables
# -----------------------------------------------------------------------------

scientific_notation_audit = pd.DataFrame(
    scientific_notation_records
)

mic_precision_artifact_audit = pd.DataFrame(
    precision_artifact_records
)

unparseable_mic_audit = pd.DataFrame(
    unparseable_mic_records
)


# -----------------------------------------------------------------------------
# Create an overall frequency summary
# -----------------------------------------------------------------------------

total_possible_mic_cells = (
    len(combined) * len(mic_columns)
)

scientific_notation_cell_count = (
    len(scientific_notation_audit)
)

precision_artifact_cell_count = (
    len(mic_precision_artifact_audit)
)

if mic_precision_artifact_audit.empty:
    affected_row_count = 0
else:
    affected_row_count = (
        mic_precision_artifact_audit["DataFrame Index"]
        .nunique()
    )


mic_precision_overall_summary = pd.DataFrame(
    {
        "Measure": [
            "Database rows",
            "MIC columns inspected",
            "Possible MIC cells",
            "Observed non-missing MIC values",
            "Scientific-notation MIC cells",
            "Long precision-artifact cells",
            "Rows containing a precision artifact",
            "Unparseable MIC cells",
        ],
        "Count": [
            len(combined),
            len(mic_columns),
            total_possible_mic_cells,
            total_observed_mic_values,
            scientific_notation_cell_count,
            precision_artifact_cell_count,
            affected_row_count,
            len(unparseable_mic_audit),
        ],
    }
)


if total_observed_mic_values > 0:
    artifact_percent_of_observed_mics = (
        precision_artifact_cell_count
        / total_observed_mic_values
        * 100
    )
else:
    artifact_percent_of_observed_mics = 0.0


if len(combined) > 0:
    artifact_percent_of_rows = (
        affected_row_count
        / len(combined)
        * 100
    )
else:
    artifact_percent_of_rows = 0.0


# -----------------------------------------------------------------------------
# Create a summary by antibiotic
# -----------------------------------------------------------------------------

antibiotic_precision_summary_records = []

for mic_column in mic_columns:

    mic_values = (
        combined[mic_column]
        .astype("string")
        .str.strip()
        .replace("", pd.NA)
    )

    observed_count = int(
        mic_values.notna().sum()
    )

    if mic_precision_artifact_audit.empty:
        artifact_count = 0
    else:
        artifact_count = int(
            mic_precision_artifact_audit[
                "Antibiotic Name"
            ]
            .eq(mic_column)
            .sum()
        )

    if artifact_count == 0:
        continue

    artifact_percent = (
        artifact_count / observed_count * 100
        if observed_count > 0
        else 0.0
    )

    antibiotic_precision_summary_records.append(
        {
            "Antibiotic Name": mic_column,
            "Observed MIC Values": observed_count,
            "Precision-Artifact Cells": artifact_count,
            "Percent of Observed MIC Values": round(
                artifact_percent,
                3,
            ),
        }
    )


mic_precision_by_antibiotic = (
    pd.DataFrame(antibiotic_precision_summary_records)
    .sort_values(
        by=[
            "Precision-Artifact Cells",
            "Antibiotic Name",
        ],
        ascending=[
            False,
            True,
        ],
    )
    .reset_index(drop=True)
    if antibiotic_precision_summary_records
    else pd.DataFrame(
        columns=[
            "Antibiotic Name",
            "Observed MIC Values",
            "Precision-Artifact Cells",
            "Percent of Observed MIC Values",
        ]
    )
)


# -----------------------------------------------------------------------------
# Create a summary by source database
# -----------------------------------------------------------------------------

source_precision_summary_records = []

if "Source Database" in combined.columns:

    for source_database, source_data in combined.groupby(
        "Source Database",
        dropna=False,
    ):

        source_observed_mic_count = sum(
            int(
                source_data[mic_column]
                .astype("string")
                .str.strip()
                .replace("", pd.NA)
                .notna()
                .sum()
            )
            for mic_column in mic_columns
        )

        if mic_precision_artifact_audit.empty:
            source_artifact_count = 0
            source_affected_row_count = 0

        else:
            source_artifact_mask = (
                mic_precision_artifact_audit[
                    "Source Database"
                ]
                .eq(source_database)
            )

            source_artifact_count = int(
                source_artifact_mask.sum()
            )

            source_affected_row_count = int(
                mic_precision_artifact_audit.loc[
                    source_artifact_mask,
                    "DataFrame Index",
                ]
                .nunique()
            )

        source_precision_summary_records.append(
            {
                "Source Database": source_database,
                "Database Rows": len(source_data),
                "Observed MIC Values": (
                    source_observed_mic_count
                ),
                "Precision-Artifact Cells": (
                    source_artifact_count
                ),
                "Rows with Precision Artifacts": (
                    source_affected_row_count
                ),
                "Percent of Observed MIC Values": round(
                    (
                        source_artifact_count
                        / source_observed_mic_count
                        * 100
                    )
                    if source_observed_mic_count > 0
                    else 0.0,
                    3,
                ),
                "Percent of Source Rows": round(
                    (
                        source_affected_row_count
                        / len(source_data)
                        * 100
                    )
                    if len(source_data) > 0
                    else 0.0,
                    3,
                ),
            }
        )


mic_precision_by_source = pd.DataFrame(
    source_precision_summary_records
)


# -----------------------------------------------------------------------------
# Validate the audit
# -----------------------------------------------------------------------------

assert len(combined) == rows_before_mic_precision_audit, (
    "The database row count changed during the MIC precision audit."
)

assert combined.columns.equals(
    columns_before_mic_precision_audit
), (
    "The database columns changed during the MIC precision audit."
)


if not scientific_notation_audit.empty:

    assert (
        scientific_notation_audit[
            "Numeric Equivalence Confirmed"
        ]
        .all()
    ), (
        "At least one concise numeric representation was not "
        "numerically equivalent to its original value."
    )


assert (
    len(mic_precision_artifact_audit)
    <= len(scientific_notation_audit)
), (
    "The precision-artifact count exceeds the scientific-notation count."
)


# -----------------------------------------------------------------------------
# Report the audit results
# -----------------------------------------------------------------------------

print("=" * 80)
print("MIC PRECISION AND SCIENTIFIC-NOTATION AUDIT")
print("=" * 80)

print(
    f"MIC columns inspected: {len(mic_columns):,}"
)

print(
    "Observed non-missing MIC values: "
    f"{total_observed_mic_values:,}"
)

print(
    "MIC values using scientific notation: "
    f"{scientific_notation_cell_count:,}"
)

print(
    "Long floating-point precision artifacts: "
    f"{precision_artifact_cell_count:,}"
)

print(
    "Rows containing at least one precision artifact: "
    f"{affected_row_count:,}"
)

print(
    "Precision artifacts as a percentage of observed MIC values: "
    f"{artifact_percent_of_observed_mics:.3f}%"
)

print(
    "Rows with precision artifacts as a percentage of database rows: "
    f"{artifact_percent_of_rows:.3f}%"
)

print(
    "MIC values that could not be parsed as a numeric value with "
    f"an optional operator: {len(unparseable_mic_audit):,}"
)


print("\nOverall MIC precision summary:")
display(mic_precision_overall_summary)


print("\nMIC precision artifacts by source database:")
display(mic_precision_by_source)


print("\nMIC precision artifacts by antibiotic:")
display(mic_precision_by_antibiotic)


print("\nComplete scientific-notation audit:")
if scientific_notation_audit.empty:
    print("No MIC values using scientific notation were identified.")
else:
    display(
        scientific_notation_audit.sort_values(
            by=[
                "Long Precision Artifact",
                "Antibiotic Name",
                "Raw MIC Value",
            ],
            ascending=[
                False,
                True,
                True,
            ],
        )
    )


print("\nLong floating-point precision-artifact audit:")
if mic_precision_artifact_audit.empty:
    print(
        "No long floating-point MIC representations were identified."
    )
else:
    display(
        mic_precision_artifact_audit.sort_values(
            by=[
                "Antibiotic Name",
                "Raw MIC Value",
            ]
        )
    )


print("\nUnparseable MIC values:")
if unparseable_mic_audit.empty:
    print(
        "All observed MIC values were compatible with the expected "
        "numeric/operator format."
    )
else:
    display(unparseable_mic_audit)


print(
    "\nAudit completed without modifying any original MIC values."
)

# =============================================================================
# EXTRACT AND AUDIT ALL UNIQUE COUNTRY VALUES
# =============================================================================
#
# Purpose:
# - Extract every unique Country value from the complete merged database.
# - Report the number of records associated with each country.
# - Show country representation by source database.
# - identify missing, blank, whitespace-affected, and case-variant labels.
# - Produce the complete country list needed to construct an explicit
#   country-to-continent crosswalk.
#
# Important:
# - This section does not change Country, Continent, or any other variable.
# - No country names are automatically corrected or standardized.
# =============================================================================

import pandas as pd
from IPython.display import display


# -----------------------------------------------------------------------------
# Confirm that the Country column exists
# -----------------------------------------------------------------------------

if "Country" not in combined.columns:
    raise KeyError(
        "The required column 'Country' was not found in the combined database."
    )


# Preserve database information for validation
rows_before_country_audit = len(combined)
columns_before_country_audit = combined.columns.copy()

country_before_audit = (
    combined["Country"].copy()
)


# -----------------------------------------------------------------------------
# Prepare original and normalized versions for comparison
# -----------------------------------------------------------------------------
#
# The normalized version is used only to identify possible formatting variants.
# It is not written back to the combined database.
# -----------------------------------------------------------------------------

country_original = (
    combined["Country"]
    .astype("string")
)

country_normalized_for_audit = (
    country_original
    .str.strip()
    .str.replace(
        r"\s+",
        " ",
        regex=True,
    )
)

country_comparison_key = (
    country_normalized_for_audit
    .str.casefold()
)


# -----------------------------------------------------------------------------
# Count missing and blank Country values
# -----------------------------------------------------------------------------

missing_country_count = int(
    country_original.isna().sum()
)

blank_country_mask = (
    country_original.notna()
    & country_original.str.strip().eq("")
)

blank_country_count = int(
    blank_country_mask.sum()
)


# -----------------------------------------------------------------------------
# Create the complete unique-Country frequency table
# -----------------------------------------------------------------------------

unique_country_values = (
    country_original
    .value_counts(dropna=False)
    .rename_axis("Country")
    .reset_index(name="Row Count")
)

unique_country_values["Percent of Database"] = (
    unique_country_values["Row Count"]
    .div(len(combined))
    .mul(100)
    .round(3)
)

unique_country_values = (
    unique_country_values
    .sort_values(
        by="Country",
        key=lambda column: (
            column.astype("string").str.casefold()
        ),
        na_position="last",
    )
    .reset_index(drop=True)
)


# -----------------------------------------------------------------------------
# Create a normalized country list for comparison
# -----------------------------------------------------------------------------

normalized_unique_country_values = (
    country_normalized_for_audit
    .mask(
        country_normalized_for_audit.eq("")
    )
    .value_counts(dropna=False)
    .rename_axis("Normalized Country")
    .reset_index(name="Row Count")
)

normalized_unique_country_values = (
    normalized_unique_country_values
    .sort_values(
        by="Normalized Country",
        key=lambda column: (
            column.astype("string").str.casefold()
        ),
        na_position="last",
    )
    .reset_index(drop=True)
)


# -----------------------------------------------------------------------------
# Identify whitespace or formatting problems
# -----------------------------------------------------------------------------

country_format_issue_mask = (
    country_original.notna()
    & country_original.ne(country_normalized_for_audit)
)

country_format_issues = (
    pd.DataFrame(
        {
            "Original Country Value": country_original,
            "Normalized for Review": (
                country_normalized_for_audit
            ),
        }
    )
    .loc[country_format_issue_mask]
    .value_counts(dropna=False)
    .rename("Row Count")
    .reset_index()
    .sort_values(
        by="Original Country Value",
        key=lambda column: (
            column.astype("string").str.casefold()
        ),
    )
    .reset_index(drop=True)
)


# -----------------------------------------------------------------------------
# Identify labels that differ only by capitalization or whitespace
# -----------------------------------------------------------------------------

country_variant_data = pd.DataFrame(
    {
        "Country": country_original,
        "Normalized Country": (
            country_normalized_for_audit
        ),
        "Comparison Key": country_comparison_key,
    }
)

country_variant_data = country_variant_data.loc[
    country_variant_data["Comparison Key"].notna()
    & country_variant_data["Comparison Key"].ne("")
].copy()


country_variant_groups = (
    country_variant_data
    .groupby(
        "Comparison Key",
        dropna=False,
    )
    .agg(
        **{
            "Observed Country Labels": (
                "Country",
                lambda values: " | ".join(
                    sorted(
                        set(values.dropna().astype(str)),
                        key=str.casefold,
                    )
                ),
            ),
            "Distinct Observed Labels": (
                "Country",
                "nunique",
            ),
            "Row Count": (
                "Country",
                "size",
            ),
        }
    )
    .reset_index(drop=True)
)

country_variant_groups = (
    country_variant_groups.loc[
        country_variant_groups[
            "Distinct Observed Labels"
        ].gt(1)
    ]
    .sort_values(
        by="Observed Country Labels",
        key=lambda column: column.str.casefold(),
    )
    .reset_index(drop=True)
)


# -----------------------------------------------------------------------------
# Create a country-by-source frequency table
# -----------------------------------------------------------------------------

if "Source Database" in combined.columns:

    country_by_source_counts = pd.crosstab(
        country_original.fillna("<MISSING>"),
        combined["Source Database"]
        .astype("string")
        .fillna("<MISSING>"),
        margins=True,
        margins_name="All Sources",
        dropna=False,
    )

    country_by_source_counts = (
        country_by_source_counts
        .sort_index(
            key=lambda index: (
                index.astype("string").str.casefold()
            )
        )
    )

else:
    country_by_source_counts = pd.DataFrame()


# -----------------------------------------------------------------------------
# Validate that the audit did not alter the database
# -----------------------------------------------------------------------------

assert len(combined) == rows_before_country_audit, (
    "The database row count changed during the Country audit."
)

assert combined.columns.equals(
    columns_before_country_audit
), (
    "The database columns changed during the Country audit."
)

assert combined["Country"].equals(
    country_before_audit
), (
    "The Country column changed during the Country audit."
)

assert unique_country_values["Row Count"].sum() == len(combined), (
    "The unique-Country counts do not sum to the database row count."
)


# -----------------------------------------------------------------------------
# Report the results
# -----------------------------------------------------------------------------

print("=" * 80)
print("COUNTRY VALUE AUDIT")
print("=" * 80)

print(f"Database rows: {len(combined):,}")

print(
    "Unique non-missing Country values: "
    f"{country_original.nunique(dropna=True):,}"
)

print(
    "Unique Country values after temporary whitespace normalization: "
    f"{country_normalized_for_audit.nunique(dropna=True):,}"
)

print(
    f"Missing Country values: {missing_country_count:,}"
)

print(
    f"Blank but non-missing Country values: {blank_country_count:,}"
)

print(
    "Rows with leading, trailing, or repeated whitespace: "
    f"{int(country_format_issue_mask.sum()):,}"
)

print(
    "Groups containing capitalization or whitespace variants: "
    f"{len(country_variant_groups):,}"
)


# Print the complete list without notebook display truncation.
print("\n" + "=" * 80)
print("COMPLETE UNIQUE COUNTRY VALUES")
print("=" * 80)

print(
    unique_country_values.to_string(
        index=False
    )
)


print("\n" + "=" * 80)
print("COUNTRY FORMATTING ISSUES")
print("=" * 80)

if country_format_issues.empty:
    print("No country formatting issues were identified.")
else:
    print(
        country_format_issues.to_string(
            index=False
        )
    )


print("\n" + "=" * 80)
print("COUNTRY LABEL VARIANTS")
print("=" * 80)

if country_variant_groups.empty:
    print(
        "No country labels differing only by capitalization "
        "or whitespace were identified."
    )
else:
    print(
        country_variant_groups.to_string(
            index=False
        )
    )


print("\n" + "=" * 80)
print("COUNTRY COUNTS BY SOURCE DATABASE")
print("=" * 80)

if country_by_source_counts.empty:
    print(
        "Source Database was not available; "
        "the source-specific table was not created."
    )
else:
    print(
        country_by_source_counts.to_string()
    )


print(
    "\nCountry audit completed without modifying the database."
)

# =============================================================================
# SECTION 2: HARMONIZE COUNTRY-TO-CONTINENT MAPPING
# =============================================================================
#
# Purpose:
# - Assign every observed Country to a geographic continent.
# - Preserve the previously existing Continent values.
# - Update the harmonized Continent column using an explicit crosswalk.
# - Stop before updating if any country is absent from the crosswalk.
# - Audit disagreements between existing and newly assigned values.
# - Validate that Country values and database rows remain unchanged.
#
# Geographic categories:
# - Africa
# - Asia
# - Europe
# - North America
# - South America
# - Oceania
#
# Specific conventions:
# - Russia is assigned to Europe.
# - Israel and Turkey are assigned to Asia.
# - Egypt is assigned to Africa.
# - Central America and the Caribbean are assigned to North America.
#
# Reference:
# - United Nations Statistics Division M49 geographic regions
# - Adapted by dividing the Americas into North and South America
# - Accessed July 15, 2026
# =============================================================================

import pandas as pd
from IPython.display import display


# -----------------------------------------------------------------------------
# Confirm that the required columns exist
# -----------------------------------------------------------------------------

required_columns = [
    "Country",
    "Continent",
]

missing_required_columns = [
    column
    for column in required_columns
    if column not in combined.columns
]

if missing_required_columns:
    raise KeyError(
        "The following required columns were not found: "
        + ", ".join(missing_required_columns)
    )


# Preserve validation information
rows_before_continent_harmonization = len(combined)

country_before_continent_harmonization = (
    combined["Country"].copy()
)

continent_immediately_before_update = (
    combined["Continent"]
    .astype("string")
    .copy()
)


# -----------------------------------------------------------------------------
# Normalize Country temporarily for exact crosswalk matching
# -----------------------------------------------------------------------------
#
# This temporary normalization removes surrounding whitespace and collapses
# repeated internal whitespace. It does not overwrite Country.
# -----------------------------------------------------------------------------

country_used_for_mapping = (
    combined["Country"]
    .astype("string")
    .str.strip()
    .str.replace(
        r"\s+",
        " ",
        regex=True,
    )
    .mask(
        lambda column: column.eq("")
    )
)


# -----------------------------------------------------------------------------
# Define the explicit country-to-continent crosswalk
# -----------------------------------------------------------------------------

country_to_continent = {

    # =========================================================================
    # Africa
    # =========================================================================

    "Cameroon": "Africa",
    "Egypt": "Africa",
    "Ghana": "Africa",
    "Ivory Coast": "Africa",
    "Kenya": "Africa",
    "Malawi": "Africa",
    "Mauritius": "Africa",
    "Morocco": "Africa",
    "Namibia": "Africa",
    "Nigeria": "Africa",
    "South Africa": "Africa",
    "Tunisia": "Africa",
    "Uganda": "Africa",

    # =========================================================================
    # Asia
    # =========================================================================

    "China": "Asia",
    "Hong Kong": "Asia",
    "India": "Asia",
    "Indonesia": "Asia",
    "Israel": "Asia",
    "Japan": "Asia",
    "Jordan": "Asia",
    "Kuwait": "Asia",
    "Lebanon": "Asia",
    "Malaysia": "Asia",
    "Oman": "Asia",
    "Pakistan": "Asia",
    "Philippines": "Asia",
    "Qatar": "Asia",
    "Saudi Arabia": "Asia",
    "Singapore": "Asia",
    "South Korea": "Asia",
    "Taiwan": "Asia",
    "Thailand": "Asia",
    "Turkey": "Asia",
    "Vietnam": "Asia",

    # =========================================================================
    # Europe
    # =========================================================================

    "Austria": "Europe",
    "Belarus": "Europe",
    "Belgium": "Europe",
    "Bulgaria": "Europe",
    "Croatia": "Europe",
    "Czech Republic": "Europe",
    "Denmark": "Europe",
    "Estonia": "Europe",
    "Finland": "Europe",
    "France": "Europe",
    "Germany": "Europe",
    "Greece": "Europe",
    "Hungary": "Europe",
    "Ireland": "Europe",
    "Italy": "Europe",
    "Latvia": "Europe",
    "Lithuania": "Europe",
    "Netherlands": "Europe",
    "Norway": "Europe",
    "Poland": "Europe",
    "Portugal": "Europe",
    "Romania": "Europe",
    "Russia": "Europe",
    "Serbia": "Europe",
    "Slovak Republic": "Europe",
    "Slovenia": "Europe",
    "Spain": "Europe",
    "Sweden": "Europe",
    "Switzerland": "Europe",
    "Ukraine": "Europe",
    "United Kingdom": "Europe",

    # =========================================================================
    # North America
    # =========================================================================

    "Canada": "North America",
    "Costa Rica": "North America",
    "Dominican Republic": "North America",
    "El Salvador": "North America",
    "Guatemala": "North America",
    "Honduras": "North America",
    "Jamaica": "North America",
    "Mexico": "North America",
    "Nicaragua": "North America",
    "Panama": "North America",
    "Puerto Rico": "North America",
    "United States": "North America",

    # =========================================================================
    # South America
    # =========================================================================

    "Argentina": "South America",
    "Brazil": "South America",
    "Chile": "South America",
    "Colombia": "South America",
    "Venezuela": "South America",

    # =========================================================================
    # Oceania
    # =========================================================================

    "Australia": "Oceania",
    "New Zealand": "Oceania",
}


# Confirm that the crosswalk contains no duplicate keys.
# A Python dictionary cannot retain duplicate keys, so the explicit total is
# also checked against the 84 countries identified in the complete database.
expected_crosswalk_country_count = 84

if len(country_to_continent) != expected_crosswalk_country_count:
    raise ValueError(
        "The country-to-continent crosswalk does not contain the expected "
        f"{expected_crosswalk_country_count} countries. "
        f"Observed crosswalk size: {len(country_to_continent)}."
    )


# Convert the dictionary into an auditable crosswalk
country_continent_crosswalk = (
    pd.DataFrame(
        country_to_continent.items(),
        columns=[
            "Country",
            "Assigned Continent",
        ],
    )
    .sort_values(
        by="Country",
        key=lambda column: column.str.casefold(),
    )
    .reset_index(drop=True)
)

country_continent_crosswalk["Reference Standard"] = (
    "UN M49 geographic regions, adapted to separate "
    "North and South America"
)

country_continent_crosswalk["Reference Access Date"] = (
    "2026-07-15"
)


# -----------------------------------------------------------------------------
# Confirm that every observed country is included in the crosswalk
# -----------------------------------------------------------------------------

observed_countries = set(
    country_used_for_mapping
    .dropna()
    .unique()
)

mapped_countries = set(
    country_to_continent
)

unmapped_countries = sorted(
    observed_countries - mapped_countries,
    key=str.casefold,
)

unused_crosswalk_countries = sorted(
    mapped_countries - observed_countries,
    key=str.casefold,
)


if unmapped_countries:

    unmapped_country_table = (
        country_used_for_mapping.loc[
            country_used_for_mapping.isin(
                unmapped_countries
            )
        ]
        .value_counts(dropna=False)
        .rename_axis("Unmapped Country")
        .reset_index(name="Row Count")
    )

    print(
        "\nThe following observed countries are absent from "
        "the country-to-continent crosswalk:"
    )

    display(unmapped_country_table)

    raise ValueError(
        "Continent harmonization stopped before updating the database. "
        "Add and review explicit mappings for every unmapped country."
    )


# -----------------------------------------------------------------------------
# Generate the harmonized Continent values
# -----------------------------------------------------------------------------

mapped_continent = (
    country_used_for_mapping
    .map(country_to_continent)
    .astype("string")
)


# -----------------------------------------------------------------------------
# Preserve the original Continent field
# -----------------------------------------------------------------------------
#
# Continent_original is created only once. Rerunning this cell will not
# overwrite the preserved source values.
# -----------------------------------------------------------------------------

continent_original_created = False

if "Continent_original" not in combined.columns:

    continent_column_position = (
        combined.columns.get_loc("Continent") + 1
    )

    combined.insert(
        continent_column_position,
        "Continent_original",
        combined["Continent"].copy(),
    )

    continent_original_created = True


# Preserve an exact snapshot for validation.
continent_original_snapshot = (
    combined["Continent_original"]
    .copy(deep=True)
)

# Create a string-compatible version for comparisons and audit tables.
continent_original = (
    continent_original_snapshot
    .astype("string")
)


# -----------------------------------------------------------------------------
# Identify disagreements with existing non-missing Continent values
# -----------------------------------------------------------------------------

existing_continent_disagreement_mask = (
    continent_original.notna()
    & mapped_continent.notna()
    & continent_original.ne(mapped_continent)
)


existing_continent_disagreements = (
    pd.DataFrame(
        {
            "Country": country_before_continent_harmonization,
            "Existing Continent": continent_original,
            "Assigned Continent": mapped_continent,
        }
    )
    .loc[existing_continent_disagreement_mask]
    .value_counts(dropna=False)
    .rename("Row Count")
    .reset_index()
    .sort_values(
        by=[
            "Country",
            "Existing Continent",
        ],
        key=lambda column: (
            column.astype("string").str.casefold()
        ),
    )
    .reset_index(drop=True)
)


# -----------------------------------------------------------------------------
# Calculate how the update will affect the current Continent field
# -----------------------------------------------------------------------------

newly_filled_continent_mask = (
    continent_immediately_before_update.isna()
    & mapped_continent.notna()
)

changed_nonmissing_continent_mask = (
    continent_immediately_before_update.notna()
    & mapped_continent.notna()
    & continent_immediately_before_update.ne(
        mapped_continent
    )
)

any_continent_change_mask = (
    continent_immediately_before_update
    .fillna("<MISSING>")
    .ne(
        mapped_continent.fillna("<MISSING>")
    )
)


# -----------------------------------------------------------------------------
# Update the harmonized Continent column
# -----------------------------------------------------------------------------

combined["Continent"] = mapped_continent


# -----------------------------------------------------------------------------
# Create the final country-to-continent audit
# -----------------------------------------------------------------------------

country_continent_audit = (
    pd.DataFrame(
        {
            "Country": country_before_continent_harmonization,
            "Country Used for Mapping": country_used_for_mapping,
            "Continent_original": continent_original,
            "Continent": combined["Continent"],
        }
    )
    .value_counts(dropna=False)
    .rename("Row Count")
    .reset_index()
    .sort_values(
        by=[
            "Continent",
            "Country",
        ],
        key=lambda column: (
            column.astype("string").str.casefold()
        ),
        na_position="last",
    )
    .reset_index(drop=True)
)


# -----------------------------------------------------------------------------
# Create the final Continent frequency summary
# -----------------------------------------------------------------------------

continent_summary = (
    combined["Continent"]
    .value_counts(dropna=False)
    .rename_axis("Continent")
    .reset_index(name="Row Count")
)

continent_summary["Percent of Database"] = (
    continent_summary["Row Count"]
    .div(len(combined))
    .mul(100)
    .round(2)
)


# -----------------------------------------------------------------------------
# Create a country-by-continent summary
# -----------------------------------------------------------------------------

country_continent_summary = (
    pd.DataFrame(
        {
            "Country": country_used_for_mapping,
            "Continent": combined["Continent"],
        }
    )
    .value_counts(dropna=False)
    .rename("Row Count")
    .reset_index()
    .sort_values(
        by=[
            "Continent",
            "Country",
        ],
        key=lambda column: (
            column.astype("string").str.casefold()
        ),
        na_position="last",
    )
    .reset_index(drop=True)
)


# -----------------------------------------------------------------------------
# Validate the harmonization
# -----------------------------------------------------------------------------

allowed_continents = {
    "Africa",
    "Asia",
    "Europe",
    "North America",
    "South America",
    "Oceania",
}


assert len(combined) == rows_before_continent_harmonization, (
    "The database row count changed during continent harmonization."
)

assert combined["Country"].equals(
    country_before_continent_harmonization
), (
    "The original Country column changed during continent harmonization."
)

assert (
    combined.loc[
        country_used_for_mapping.notna(),
        "Continent",
    ]
    .notna()
    .all()
), (
    "At least one non-missing Country did not receive a Continent."
)

unexpected_continent_values = (
    set(
        combined["Continent"]
        .dropna()
        .unique()
    )
    - allowed_continents
)

assert not unexpected_continent_values, (
    "Unexpected Continent values were generated: "
    + ", ".join(
        sorted(unexpected_continent_values)
    )
)

assert country_continent_audit["Row Count"].sum() == len(combined), (
    "The country-to-continent audit does not sum to the database row count."
)

assert country_continent_summary["Row Count"].sum() == len(combined), (
    "The country-continent summary does not sum to the database row count."
)

assert combined["Continent_original"].equals(
    continent_original_snapshot
), (
    "The preserved Continent_original field changed "
    "during harmonization."
)


# -----------------------------------------------------------------------------
# Report the results
# -----------------------------------------------------------------------------

print("=" * 80)
print("COUNTRY-TO-CONTINENT HARMONIZATION")
print("=" * 80)

print(f"Database rows: {len(combined):,}")

print(
    "Unique observed countries: "
    f"{len(observed_countries):,}"
)

print(
    "Countries in the explicit crosswalk: "
    f"{len(country_to_continent):,}"
)

print(
    "Unmapped observed countries: "
    f"{len(unmapped_countries):,}"
)

print(
    "Unused crosswalk entries: "
    f"{len(unused_crosswalk_countries):,}"
)

print(
    "Missing Continent values before update: "
    f"{int(continent_immediately_before_update.isna().sum()):,}"
)

print(
    "Missing Continent values after update: "
    f"{int(combined['Continent'].isna().sum()):,}"
)

print(
    "Previously missing Continent values filled: "
    f"{int(newly_filled_continent_mask.sum()):,}"
)

print(
    "Existing non-missing Continent values changed: "
    f"{int(changed_nonmissing_continent_mask.sum()):,}"
)

print(
    "Rows with any Continent change: "
    f"{int(any_continent_change_mask.sum()):,}"
)

print(
    "Disagreements with preserved Continent_original values: "
    f"{int(existing_continent_disagreement_mask.sum()):,}"
)

print(
    "Continent_original created during this run: "
    f"{continent_original_created}"
)


print("\nComplete country-to-continent crosswalk:")
display(country_continent_crosswalk)


print("\nExisting non-missing Continent disagreements:")
if existing_continent_disagreements.empty:
    print(
        "No existing non-missing values disagreed with "
        "the selected geographic convention."
    )
else:
    display(existing_continent_disagreements)


if unused_crosswalk_countries:
    print("\nUnused crosswalk countries:")
    for country_name in unused_crosswalk_countries:
        print(f"  - {country_name}")


print("\nFinal Continent frequency summary:")
display(continent_summary)


print("\nFinal country-to-continent summary:")
display(country_continent_summary)


print("\nComplete row-count audit:")
display(country_continent_audit)


print(
    "\nCountry-to-continent harmonization completed successfully."
)

# =============================================================================
# SAVE THE FINAL HARMONIZED DATABASE
# =============================================================================

# -----------------------------------------------------------------------------
# Define the new output path
# -----------------------------------------------------------------------------

output_file = Path(
    "/content/drive/MyDrive/AMR Data Challenge 2026/"
    "Harmonized Database Creation/Combined_v2/"
    "AMR_combined_harmonized_v2.csv"
)


# -----------------------------------------------------------------------------
# Run final pre-save validation checks
# -----------------------------------------------------------------------------

if "Organism_clean" not in combined.columns:
    raise KeyError(
        "The 'Organism_clean' column is missing. "
        "Run the organism harmonization section before saving."
    )


if combined.columns.duplicated().any():
    duplicated_columns = combined.columns[
        combined.columns.duplicated(keep=False)
    ].tolist()

    raise ValueError(
        f"Duplicate column names were detected: {duplicated_columns}"
    )


# Confirm that every interpretation column has a corresponding MIC column
interpretation_columns = [
    column
    for column in combined.columns
    if str(column).endswith("_I")
]

missing_mic_columns = [
    interpretation_column[:-2]
    for interpretation_column in interpretation_columns
    if interpretation_column[:-2] not in combined.columns
]

if missing_mic_columns:
    raise ValueError(
        "The following interpretation columns do not have matching MIC "
        f"columns: {missing_mic_columns}"
    )


# Confirm that harmonization did not introduce missing organism values
original_missing = combined["Organism"].isna().sum()
clean_missing = combined["Organism_clean"].isna().sum()

if original_missing != clean_missing:
    raise ValueError(
        "The number of missing values differs between 'Organism' and "
        "'Organism_clean'."
    )


print("Pre-save validation completed successfully.")
print(f"Rows to save: {len(combined):,}")
print(f"Columns to save: {len(combined.columns):,}")
print(
    f"Unique cleaned organism labels: "
    f"{combined['Organism_clean'].nunique(dropna=True):,}"
)


# -----------------------------------------------------------------------------
# Prevent accidental overwriting
# -----------------------------------------------------------------------------

if output_file.exists():
    raise FileExistsError(
        f"The output file already exists:\n{output_file}\n\n"
        "Choose a new filename or deliberately remove the existing file."
    )


# -----------------------------------------------------------------------------
# Save the finalized database
# -----------------------------------------------------------------------------

combined.to_csv(
    output_file,
    index=False,
    encoding="utf-8",
)


print("\nDatabase saved successfully.")
print(f"Output file: {output_file}")
print(
    f"File size: {output_file.stat().st_size / (1024 ** 2):,.1f} MB"
)

# =============================================================================
# VERIFY THE SAVED CSV FILE
# =============================================================================

# Read only the header
saved_columns = pd.read_csv(
    output_file,
    nrows=0,
).columns.tolist()


if saved_columns != combined.columns.tolist():
    raise ValueError(
        "The saved CSV columns do not exactly match the dataframe columns."
    )


# Count saved rows in memory-efficient chunks
saved_row_count = 0
saved_missing_organism_clean = 0

for chunk in pd.read_csv(
    output_file,
    usecols=["Organism_clean"],
    chunksize=100_000,
    low_memory=False,
):
    saved_row_count += len(chunk)
    saved_missing_organism_clean += (
        chunk["Organism_clean"].isna().sum()
    )


# Validate the saved row count
if saved_row_count != len(combined):
    raise ValueError(
        f"Row-count mismatch: dataframe has {len(combined):,} rows, "
        f"but saved CSV has {saved_row_count:,} rows."
    )


# Validate missingness
if saved_missing_organism_clean != clean_missing:
    raise ValueError(
        "The number of missing Organism_clean values changed after saving."
    )


print("Saved CSV verification completed successfully.")
print(f"Verified rows: {saved_row_count:,}")
print(f"Verified columns: {len(saved_columns):,}")
print(
    f"Missing Organism_clean values: "
    f"{saved_missing_organism_clean:,}"
)

